; AnimationTypePointerTable indexes (see engine/battle/animations.asm)
	; 1
DEF ANIMATIONTYPE_SHAKE_SCREEN_VERTICALLY EQU 1
	; 2
DEF ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_HEAVY EQU 2
	; 3
DEF ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_SLOW EQU 3
	; 4
DEF ANIMATIONTYPE_BLINK_ENEMY_MON_SPRITE EQU 4
	; 5
DEF ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_LIGHT EQU 5
	; 6
DEF ANIMATIONTYPE_SHAKE_SCREEN_HORIZONTALLY_SLOW_2 EQU 6
