; CreditsTextPointers indexes (see data/credits/credits_text.asm)
	; $00
DEF CRED_VERSION EQU 0
	; $01
DEF CRED_TAJIRI EQU 1
	; $02
DEF CRED_TA_OOTA EQU 2
	; $03
DEF CRED_MORIMOTO EQU 3
	; $04
DEF CRED_WATANABE EQU 4
	; $05
DEF CRED_MASUDE EQU 5
	; $06
DEF CRED_NISINO EQU 6
	; $07
DEF CRED_SUGIMORI EQU 7
	; $08
DEF CRED_NISHIDA EQU 8
	; $09
DEF CRED_MIYAMOTO EQU 9
	; $0A
DEF CRED_KAWAGUCHI EQU $A
	; $0B
DEF CRED_ISHIHARA EQU $B
	; $0C
DEF CRED_YAMAUCHI EQU $C
	; $0D
DEF CRED_ZINNAI EQU $D
	; $0E
DEF CRED_HISHIDA EQU $E
	; $0F
DEF CRED_SAKAI EQU $F
	; $10
DEF CRED_YAMAGUCHI EQU $10
	; $11
DEF CRED_YAMAMOTO EQU $11
	; $12
DEF CRED_TANIGUCHI EQU $12
	; $13
DEF CRED_NONOMURA EQU $13
	; $14
DEF CRED_FUZIWARA EQU $14
	; $15
DEF CRED_MATSUSIMA EQU $15
	; $16
DEF CRED_TOMISAWA EQU $16
	; $17
DEF CRED_KAWAMOTO EQU $17
	; $18
DEF CRED_KAKEI EQU $18
	; $19
DEF CRED_TSUCHIYA EQU $19
	; $1A
DEF CRED_TA_NAKAMURA EQU $1A
	; $1B
DEF CRED_YUDA EQU $1B
	; $1C
DEF CRED_MON EQU $1C
	; $1D
DEF CRED_DIRECTOR EQU $1D
	; $1E
DEF CRED_PROGRAMMERS EQU $1E
	; $1F
DEF CRED_CHAR_DESIGN EQU $1F
	; $20
DEF CRED_MUSIC EQU $20
	; $21
DEF CRED_SOUND_EFFECTS EQU $21
	; $22
DEF CRED_GAME_DESIGN EQU $22
	; $23
DEF CRED_MONSTER_DESIGN EQU $23
	; $24
DEF CRED_GAME_SCENE EQU $24
	; $25
DEF CRED_PARAM EQU $25
	; $26
DEF CRED_MAP EQU $26
	; $27
DEF CRED_TEST EQU $27
	; $28
DEF CRED_SPECIAL EQU $28
	; $29
DEF CRED_PRODUCERS EQU $29
	; $2A
DEF CRED_PRODUCER EQU $2A
	; $2B
DEF CRED_EXECUTIVE EQU $2B
	; $2C
DEF CRED_TAMADA EQU $2C
	; $2D
DEF CRED_SA_OOTA EQU $2D
	; $2E
DEF CRED_YOSHIKAWA EQU $2E
	; $2F
DEF CRED_TO_OOTA EQU $2F
	; $30
DEF CRED_US_STAFF EQU $30
	; $31
DEF CRED_US_COORD EQU $31
	; $32
DEF CRED_TILDEN EQU $32
	; $33
DEF CRED_KAWAKAMI EQU $33
	; $34
DEF CRED_HI_NAKAMURA EQU $34
	; $35
DEF CRED_GIESE EQU $35
	; $36
DEF CRED_OSBORNE EQU $36
	; $37
DEF CRED_TRANS EQU $37
	; $38
DEF CRED_OGASAWARA EQU $38
	; $39
DEF CRED_IWATA EQU $39
	; $3A
DEF CRED_IZUSHI EQU $3A
	; $3B
DEF CRED_HARADA EQU $3B
	; $3C
DEF CRED_MURAKAWA EQU $3C
	; $3D
DEF CRED_FUKUI EQU $3D
	; $3E
DEF CRED_CLUB EQU $3E
	; $3F
DEF CRED_PAAD EQU $3F
DEF NUM_CRED_STRINGS EQU $40

	; $FF
DEF CRED_TEXT_FADE_MON EQU $FFFFFFFF
	; $FE
DEF CRED_TEXT_MON EQU $FFFFFFFE
	; $FD
DEF CRED_TEXT_FADE EQU $FFFFFFFD
	; $FC
DEF CRED_TEXT EQU $FFFFFFFC
	; $FB
DEF CRED_COPYRIGHT EQU $FFFFFFFB
	; $FA
DEF CRED_THE_END EQU $FFFFFFFA
