; item ids
; indexes for:
; - ItemNames (see data/items/names.asm)
; - ItemPrices (see data/items/prices.asm)
; - TechnicalMachinePrices (see data/items/tm_prices.asm)
; - KeyItemFlags (see data/items/key_items.asm)
; - ItemUsePtrTable (see engine/items/item_effects.asm)
	; $00
DEF NO_ITEM EQU 0
	; $01
DEF MASTER_BALL EQU 1
	; $02
DEF ULTRA_BALL EQU 2
	; $03
DEF GREAT_BALL EQU 3
	; $04
DEF POKE_BALL EQU 4
	; $05
DEF TOWN_MAP EQU 5
	; $06
DEF BICYCLE EQU 6
	; $07
DEF SURFBOARD EQU 7
	; $08
DEF SAFARI_BALL EQU 8
	; $09
DEF POKEDEX EQU 9
	; $0A
DEF MOON_STONE EQU $A
	; $0B
DEF ANTIDOTE EQU $B
	; $0C
DEF BURN_HEAL EQU $C
	; $0D
DEF ICE_HEAL EQU $D
	; $0E
DEF AWAKENING EQU $E
	; $0F
DEF PARLYZ_HEAL EQU $F
	; $10
DEF FULL_RESTORE EQU $10
	; $11
DEF MAX_POTION EQU $11
	; $12
DEF HYPER_POTION EQU $12
	; $13
DEF SUPER_POTION EQU $13
	; $14
DEF POTION EQU $14
; badges use item IDs (see scripts/CeruleanBadgeHouse.asm)
	; $15
DEF BOULDERBADGE EQU $15
DEF SAFARI_BAIT EQU BOULDERBADGE ; overload
	; $16
DEF CASCADEBADGE EQU $16
DEF SAFARI_ROCK EQU CASCADEBADGE ; overload
	; $17
DEF THUNDERBADGE EQU $17
	; $18
DEF RAINBOWBADGE EQU $18
	; $19
DEF SOULBADGE EQU $19
	; $1A
DEF MARSHBADGE EQU $1A
	; $1B
DEF VOLCANOBADGE EQU $1B
	; $1C
DEF EARTHBADGE EQU $1C
	; $1D
DEF ESCAPE_ROPE EQU $1D
	; $1E
DEF REPEL EQU $1E
	; $1F
DEF OLD_AMBER EQU $1F
	; $20
DEF FIRE_STONE EQU $20
	; $21
DEF THUNDER_STONE EQU $21
	; $22
DEF WATER_STONE EQU $22
	; $23
DEF HP_UP EQU $23
	; $24
DEF PROTEIN EQU $24
	; $25
DEF IRON EQU $25
	; $26
DEF CARBOS EQU $26
	; $27
DEF CALCIUM EQU $27
	; $28
DEF RARE_CANDY EQU $28
	; $29
DEF DOME_FOSSIL EQU $29
	; $2A
DEF HELIX_FOSSIL EQU $2A
	; $2B
DEF SECRET_KEY EQU $2B
	; $2C ; unused
DEF ITEM_2C EQU $2C
	; $2D
DEF BIKE_VOUCHER EQU $2D
	; $2E
DEF X_ACCURACY EQU $2E
	; $2F
DEF LEAF_STONE EQU $2F
	; $30
DEF CARD_KEY EQU $30
	; $31
DEF NUGGET EQU $31
	; $32 ; unused
DEF ITEM_32 EQU $32
	; $33
DEF POKE_DOLL EQU $33
	; $34
DEF FULL_HEAL EQU $34
	; $35
DEF REVIVE EQU $35
	; $36
DEF MAX_REVIVE EQU $36
	; $37
DEF GUARD_SPEC EQU $37
	; $38
DEF SUPER_REPEL EQU $38
	; $39
DEF MAX_REPEL EQU $39
	; $3A
DEF DIRE_HIT EQU $3A
	; $3B
DEF COIN EQU $3B
	; $3C
DEF FRESH_WATER EQU $3C
	; $3D
DEF SODA_POP EQU $3D
	; $3E
DEF LEMONADE EQU $3E
	; $3F
DEF S_S_TICKET EQU $3F
	; $40
DEF GOLD_TEETH EQU $40
	; $41
DEF X_ATTACK EQU $41
	; $42
DEF X_DEFEND EQU $42
	; $43
DEF X_SPEED EQU $43
	; $44
DEF X_SPECIAL EQU $44
	; $45
DEF COIN_CASE EQU $45
	; $46
DEF OAKS_PARCEL EQU $46
	; $47
DEF ITEMFINDER EQU $47
	; $48
DEF SILPH_SCOPE EQU $48
	; $49
DEF POKE_FLUTE EQU $49
	; $4A
DEF LIFT_KEY EQU $4A
	; $4B
DEF EXP_ALL EQU $4B
	; $4C
DEF OLD_ROD EQU $4C
	; $4D
DEF GOOD_ROD EQU $4D
	; $4E
DEF SUPER_ROD EQU $4E
	; $4F
DEF PP_UP EQU $4F
	; $50
DEF ETHER EQU $50
	; $51
DEF MAX_ETHER EQU $51
	; $52
DEF ELIXER EQU $52
	; $53
DEF MAX_ELIXER EQU $53
DEF NUM_ITEMS EQU $53

; elevator floors use item IDs (see scripts/CeladonMartElevator.asm and scripts/SilphCoElevator.asm)
	; $54
DEF FLOOR_B2F EQU $54
	; $55
DEF FLOOR_B1F EQU $55
	; $56
DEF FLOOR_1F EQU $56
	; $57
DEF FLOOR_2F EQU $57
	; $58
DEF FLOOR_3F EQU $58
	; $59
DEF FLOOR_4F EQU $59
	; $5A
DEF FLOOR_5F EQU $5A
	; $5B
DEF FLOOR_6F EQU $5B
	; $5C
DEF FLOOR_7F EQU $5C
	; $5D
DEF FLOOR_8F EQU $5D
	; $5E
DEF FLOOR_9F EQU $5E
	; $5F
DEF FLOOR_10F EQU $5F
	; $60
DEF FLOOR_11F EQU $60
	; $61
DEF FLOOR_B4F EQU $61
DEF NUM_FLOORS EQU $E


; HMs are defined before TMs, so the actual number of TM definitions
; is not yet available. The TM quantity is hard-coded here and must
; match the actual number below.
DEF NUM_TMS EQU 50




DEF HM01 EQU $C4
	; $C4
DEF HM_CUT EQU $C4
DEF HM01_MOVE EQU $F
DEF CUT_TMNUM EQU $33
	; $C5
DEF HM_FLY EQU $C5
DEF HM02_MOVE EQU $13
DEF FLY_TMNUM EQU $34
	; $C6
DEF HM_SURF EQU $C6
DEF HM03_MOVE EQU $39
DEF SURF_TMNUM EQU $35
	; $C7
DEF HM_STRENGTH EQU $C7
DEF HM04_MOVE EQU $46
DEF STRENGTH_TMNUM EQU $36
	; $C8
DEF HM_FLASH EQU $C8
DEF HM05_MOVE EQU $94
DEF FLASH_TMNUM EQU $37
DEF NUM_HMS EQU 5



DEF TM01 EQU $C9
	; $C9
DEF TM_MEGA_PUNCH EQU $C9
DEF TM01_MOVE EQU 5
DEF MEGA_PUNCH_TMNUM EQU 1
	; $CA
DEF TM_RAZOR_WIND EQU $CA
DEF TM02_MOVE EQU $D
DEF RAZOR_WIND_TMNUM EQU 2
	; $CB
DEF TM_SWORDS_DANCE EQU $CB
DEF TM03_MOVE EQU $E
DEF SWORDS_DANCE_TMNUM EQU 3
	; $CC
DEF TM_WHIRLWIND EQU $CC
DEF TM04_MOVE EQU $12
DEF WHIRLWIND_TMNUM EQU 4
	; $CD
DEF TM_MEGA_KICK EQU $CD
DEF TM05_MOVE EQU $19
DEF MEGA_KICK_TMNUM EQU 5
	; $CE
DEF TM_TOXIC EQU $CE
DEF TM06_MOVE EQU $5C
DEF TOXIC_TMNUM EQU 6
	; $CF
DEF TM_HORN_DRILL EQU $CF
DEF TM07_MOVE EQU $20
DEF HORN_DRILL_TMNUM EQU 7
	; $D0
DEF TM_BODY_SLAM EQU $D0
DEF TM08_MOVE EQU $22
DEF BODY_SLAM_TMNUM EQU 8
	; $D1
DEF TM_TAKE_DOWN EQU $D1
DEF TM09_MOVE EQU $24
DEF TAKE_DOWN_TMNUM EQU 9
	; $D2
DEF TM_DOUBLE_EDGE EQU $D2
DEF TM10_MOVE EQU $26
DEF DOUBLE_EDGE_TMNUM EQU $A
	; $D3
DEF TM_BUBBLEBEAM EQU $D3
DEF TM11_MOVE EQU $3D
DEF BUBBLEBEAM_TMNUM EQU $B
	; $D4
DEF TM_WATER_GUN EQU $D4
DEF TM12_MOVE EQU $37
DEF WATER_GUN_TMNUM EQU $C
	; $D5
DEF TM_ICE_BEAM EQU $D5
DEF TM13_MOVE EQU $3A
DEF ICE_BEAM_TMNUM EQU $D
	; $D6
DEF TM_BLIZZARD EQU $D6
DEF TM14_MOVE EQU $3B
DEF BLIZZARD_TMNUM EQU $E
	; $D7
DEF TM_HYPER_BEAM EQU $D7
DEF TM15_MOVE EQU $3F
DEF HYPER_BEAM_TMNUM EQU $F
	; $D8
DEF TM_PAY_DAY EQU $D8
DEF TM16_MOVE EQU 6
DEF PAY_DAY_TMNUM EQU $10
	; $D9
DEF TM_SUBMISSION EQU $D9
DEF TM17_MOVE EQU $42
DEF SUBMISSION_TMNUM EQU $11
	; $DA
DEF TM_COUNTER EQU $DA
DEF TM18_MOVE EQU $44
DEF COUNTER_TMNUM EQU $12
	; $DB
DEF TM_SEISMIC_TOSS EQU $DB
DEF TM19_MOVE EQU $45
DEF SEISMIC_TOSS_TMNUM EQU $13
	; $DC
DEF TM_RAGE EQU $DC
DEF TM20_MOVE EQU $63
DEF RAGE_TMNUM EQU $14
	; $DD
DEF TM_MEGA_DRAIN EQU $DD
DEF TM21_MOVE EQU $48
DEF MEGA_DRAIN_TMNUM EQU $15
	; $DE
DEF TM_SOLARBEAM EQU $DE
DEF TM22_MOVE EQU $4C
DEF SOLARBEAM_TMNUM EQU $16
	; $DF
DEF TM_DRAGON_RAGE EQU $DF
DEF TM23_MOVE EQU $52
DEF DRAGON_RAGE_TMNUM EQU $17
	; $E0
DEF TM_THUNDERBOLT EQU $E0
DEF TM24_MOVE EQU $55
DEF THUNDERBOLT_TMNUM EQU $18
	; $E1
DEF TM_THUNDER EQU $E1
DEF TM25_MOVE EQU $57
DEF THUNDER_TMNUM EQU $19
	; $E2
DEF TM_EARTHQUAKE EQU $E2
DEF TM26_MOVE EQU $59
DEF EARTHQUAKE_TMNUM EQU $1A
	; $E3
DEF TM_FISSURE EQU $E3
DEF TM27_MOVE EQU $5A
DEF FISSURE_TMNUM EQU $1B
	; $E4
DEF TM_DIG EQU $E4
DEF TM28_MOVE EQU $5B
DEF DIG_TMNUM EQU $1C
	; $E5
DEF TM_PSYCHIC_M EQU $E5
DEF TM29_MOVE EQU $5E
DEF PSYCHIC_M_TMNUM EQU $1D
	; $E6
DEF TM_TELEPORT EQU $E6
DEF TM30_MOVE EQU $64
DEF TELEPORT_TMNUM EQU $1E
	; $E7
DEF TM_MIMIC EQU $E7
DEF TM31_MOVE EQU $66
DEF MIMIC_TMNUM EQU $1F
	; $E8
DEF TM_DOUBLE_TEAM EQU $E8
DEF TM32_MOVE EQU $68
DEF DOUBLE_TEAM_TMNUM EQU $20
	; $E9
DEF TM_REFLECT EQU $E9
DEF TM33_MOVE EQU $73
DEF REFLECT_TMNUM EQU $21
	; $EA
DEF TM_BIDE EQU $EA
DEF TM34_MOVE EQU $75
DEF BIDE_TMNUM EQU $22
	; $EB
DEF TM_METRONOME EQU $EB
DEF TM35_MOVE EQU $76
DEF METRONOME_TMNUM EQU $23
	; $EC
DEF TM_SELFDESTRUCT EQU $EC
DEF TM36_MOVE EQU $78
DEF SELFDESTRUCT_TMNUM EQU $24
	; $ED
DEF TM_EGG_BOMB EQU $ED
DEF TM37_MOVE EQU $79
DEF EGG_BOMB_TMNUM EQU $25
	; $EE
DEF TM_FIRE_BLAST EQU $EE
DEF TM38_MOVE EQU $7E
DEF FIRE_BLAST_TMNUM EQU $26
	; $EF
DEF TM_SWIFT EQU $EF
DEF TM39_MOVE EQU $81
DEF SWIFT_TMNUM EQU $27
	; $F0
DEF TM_SKULL_BASH EQU $F0
DEF TM40_MOVE EQU $82
DEF SKULL_BASH_TMNUM EQU $28
	; $F1
DEF TM_SOFTBOILED EQU $F1
DEF TM41_MOVE EQU $87
DEF SOFTBOILED_TMNUM EQU $29
	; $F2
DEF TM_DREAM_EATER EQU $F2
DEF TM42_MOVE EQU $8A
DEF DREAM_EATER_TMNUM EQU $2A
	; $F3
DEF TM_SKY_ATTACK EQU $F3
DEF TM43_MOVE EQU $8F
DEF SKY_ATTACK_TMNUM EQU $2B
	; $F4
DEF TM_REST EQU $F4
DEF TM44_MOVE EQU $9C
DEF REST_TMNUM EQU $2C
	; $F5
DEF TM_THUNDER_WAVE EQU $F5
DEF TM45_MOVE EQU $56
DEF THUNDER_WAVE_TMNUM EQU $2D
	; $F6
DEF TM_PSYWAVE EQU $F6
DEF TM46_MOVE EQU $95
DEF PSYWAVE_TMNUM EQU $2E
	; $F7
DEF TM_EXPLOSION EQU $F7
DEF TM47_MOVE EQU $99
DEF EXPLOSION_TMNUM EQU $2F
	; $F8
DEF TM_ROCK_SLIDE EQU $F8
DEF TM48_MOVE EQU $9D
DEF ROCK_SLIDE_TMNUM EQU $30
	; $F9
DEF TM_TRI_ATTACK EQU $F9
DEF TM49_MOVE EQU $A1
DEF TRI_ATTACK_TMNUM EQU $31
	; $FA
DEF TM_SUBSTITUTE EQU $FA
DEF TM50_MOVE EQU $A4
DEF SUBSTITUTE_TMNUM EQU $32

DEF NUM_TM_HM EQU NUM_TMS + NUM_HMS

; 50 TMs + 5 HMs = 55 learnable TM/HM flags per Pokémon.
; These fit in 7 bytes, with one unused bit left over.
DEF UNUSED_TMNUM EQU $38

DEF MAX_HIDDEN_ITEMS EQU 112
DEF MAX_HIDDEN_COINS EQU 16
