; spritestatedata1 struct members (see macros/ram.asm)
	; 0
DEF SPRITESTATEDATA1_PICTUREID EQU 0
	; 1
DEF SPRITESTATEDATA1_MOVEMENTSTATUS EQU 1
	; 2
DEF SPRITESTATEDATA1_IMAGEINDEX EQU 2
	; 3
DEF SPRITESTATEDATA1_YSTEPVECTOR EQU 3
	; 4
DEF SPRITESTATEDATA1_YPIXELS EQU 4
	; 5
DEF SPRITESTATEDATA1_XSTEPVECTOR EQU 5
	; 6
DEF SPRITESTATEDATA1_XPIXELS EQU 6
	; 7
DEF SPRITESTATEDATA1_INTRAANIMFRAMECOUNTER EQU 7
	; 8
DEF SPRITESTATEDATA1_ANIMFRAMECOUNTER EQU 8
	; 9
DEF SPRITESTATEDATA1_FACINGDIRECTION EQU 9
	; a
DEF SPRITESTATEDATA1_YADJUSTED EQU $A
	; b
DEF SPRITESTATEDATA1_XADJUSTED EQU $B
	; c
DEF SPRITESTATEDATA1_COLLISIONDATA EQU $C
	; d
DEF SPRITESTATEDATA1_0D EQU $D
	; e
DEF SPRITESTATEDATA1_0E EQU $E
	; f
DEF SPRITESTATEDATA1_0F EQU $F
DEF SPRITESTATEDATA1_LENGTH EQU $10

; spritestatedata2 struct members (see macros/ram.asm)
	; 0
DEF SPRITESTATEDATA2_WALKANIMATIONCOUNTER EQU 0
	; 1
DEF SPRITESTATEDATA2_01 EQU 1
	; 2
DEF SPRITESTATEDATA2_YDISPLACEMENT EQU 2
	; 3
DEF SPRITESTATEDATA2_XDISPLACEMENT EQU 3
	; 4
DEF SPRITESTATEDATA2_MAPY EQU 4
	; 5
DEF SPRITESTATEDATA2_MAPX EQU 5
	; 6
DEF SPRITESTATEDATA2_MOVEMENTBYTE1 EQU 6
	; 7
DEF SPRITESTATEDATA2_GRASSPRIORITY EQU 7
	; 8
DEF SPRITESTATEDATA2_MOVEMENTDELAY EQU 8
	; 9
DEF SPRITESTATEDATA2_ORIGFACINGDIRECTION EQU 9
	; a
DEF SPRITESTATEDATA2_0A EQU $A
	; b
DEF SPRITESTATEDATA2_0B EQU $B
	; c
DEF SPRITESTATEDATA2_0C EQU $C
	; d
DEF SPRITESTATEDATA2_PICTUREID EQU $D
	; e
DEF SPRITESTATEDATA2_IMAGEBASEOFFSET EQU $E
	; f
DEF SPRITESTATEDATA2_0F EQU $F
DEF SPRITESTATEDATA2_LENGTH EQU $10

DEF NUM_SPRITESTATEDATA_STRUCTS EQU 16

	; 6
DEF BIT_TRAINER EQU 6
	; 7
DEF BIT_ITEM EQU 7

; different kinds of people events
DEF TRAINER EQU 1 << BIT_TRAINER
DEF ITEM    EQU 1 << BIT_ITEM

; movement status
DEF BIT_FACE_PLAYER EQU 7

DEF WALK EQU $FE
DEF STAY EQU $FF

DEF ANY_DIR    EQU $00
DEF UP_DOWN    EQU $01
DEF LEFT_RIGHT EQU $02
DEF DOWN       EQU $D0
DEF UP         EQU $D1
DEF LEFT       EQU $D2
DEF RIGHT      EQU $D3
DEF NONE       EQU $FF

DEF BOULDER_MOVEMENT_BYTE_2 EQU $10
