
; "Indoor" maps are grouped sequentially (see data/maps/town_map_entries.asm)
DEF NUM_INDOOR_MAP_GROUPS EQU 0

; map ids
; indexes for:
; - MapHeaderBanks (see data/maps/map_header_banks.asm)
; - MapHeaderPointers (see data/maps/map_header_pointers.asm)
; - MapSongBanks (see data/maps/songs.asm)
; - ToggleableObjectMapPointers (see data/maps/toggleable_objects.asm)
; - MapSpriteSets (see data/maps/sprite_sets.asm)
; - ExternalMapEntries (see data/maps/town_map_entries.asm)
; - WildDataPointers (see data/wild/grass_water.asm)
; Each map also has associated data in maps.asm.
; Order: towns/cities, then routes, then indoor/dungeon maps
	; $00
DEF PALLET_TOWN EQU 0
DEF PALLET_TOWN_WIDTH EQU $A
DEF PALLET_TOWN_HEIGHT EQU 9
	; $01
DEF VIRIDIAN_CITY EQU 1
DEF VIRIDIAN_CITY_WIDTH EQU $14
DEF VIRIDIAN_CITY_HEIGHT EQU $12
	; $02
DEF PEWTER_CITY EQU 2
DEF PEWTER_CITY_WIDTH EQU $14
DEF PEWTER_CITY_HEIGHT EQU $12
	; $03
DEF CERULEAN_CITY EQU 3
DEF CERULEAN_CITY_WIDTH EQU $14
DEF CERULEAN_CITY_HEIGHT EQU $12
	; $04
DEF LAVENDER_TOWN EQU 4
DEF LAVENDER_TOWN_WIDTH EQU $A
DEF LAVENDER_TOWN_HEIGHT EQU 9
	; $05
DEF VERMILION_CITY EQU 5
DEF VERMILION_CITY_WIDTH EQU $14
DEF VERMILION_CITY_HEIGHT EQU $12
	; $06
DEF CELADON_CITY EQU 6
DEF CELADON_CITY_WIDTH EQU $19
DEF CELADON_CITY_HEIGHT EQU $12
	; $07
DEF FUCHSIA_CITY EQU 7
DEF FUCHSIA_CITY_WIDTH EQU $14
DEF FUCHSIA_CITY_HEIGHT EQU $12
	; $08
DEF CINNABAR_ISLAND EQU 8
DEF CINNABAR_ISLAND_WIDTH EQU $A
DEF CINNABAR_ISLAND_HEIGHT EQU 9
	; $09
DEF INDIGO_PLATEAU EQU 9
DEF INDIGO_PLATEAU_WIDTH EQU $A
DEF INDIGO_PLATEAU_HEIGHT EQU 9
	; $0A
DEF SAFFRON_CITY EQU $A
DEF SAFFRON_CITY_WIDTH EQU $14
DEF SAFFRON_CITY_HEIGHT EQU $12
DEF NUM_CITY_MAPS EQU $B

	; $0B
DEF UNUSED_MAP_0B EQU $B
DEF UNUSED_MAP_0B_WIDTH EQU 0
DEF UNUSED_MAP_0B_HEIGHT EQU 0

DEF FIRST_ROUTE_MAP EQU $C
	; $0C
DEF ROUTE_1 EQU $C
DEF ROUTE_1_WIDTH EQU $A
DEF ROUTE_1_HEIGHT EQU $12
	; $0D
DEF ROUTE_2 EQU $D
DEF ROUTE_2_WIDTH EQU $A
DEF ROUTE_2_HEIGHT EQU $24
	; $0E
DEF ROUTE_3 EQU $E
DEF ROUTE_3_WIDTH EQU $23
DEF ROUTE_3_HEIGHT EQU 9
	; $0F
DEF ROUTE_4 EQU $F
DEF ROUTE_4_WIDTH EQU $2D
DEF ROUTE_4_HEIGHT EQU 9
	; $10
DEF ROUTE_5 EQU $10
DEF ROUTE_5_WIDTH EQU $A
DEF ROUTE_5_HEIGHT EQU $12
	; $11
DEF ROUTE_6 EQU $11
DEF ROUTE_6_WIDTH EQU $A
DEF ROUTE_6_HEIGHT EQU $12
	; $12
DEF ROUTE_7 EQU $12
DEF ROUTE_7_WIDTH EQU $A
DEF ROUTE_7_HEIGHT EQU 9
	; $13
DEF ROUTE_8 EQU $13
DEF ROUTE_8_WIDTH EQU $1E
DEF ROUTE_8_HEIGHT EQU 9
	; $14
DEF ROUTE_9 EQU $14
DEF ROUTE_9_WIDTH EQU $1E
DEF ROUTE_9_HEIGHT EQU 9
	; $15
DEF ROUTE_10 EQU $15
DEF ROUTE_10_WIDTH EQU $A
DEF ROUTE_10_HEIGHT EQU $24
	; $16
DEF ROUTE_11 EQU $16
DEF ROUTE_11_WIDTH EQU $1E
DEF ROUTE_11_HEIGHT EQU 9
	; $17
DEF ROUTE_12 EQU $17
DEF ROUTE_12_WIDTH EQU $A
DEF ROUTE_12_HEIGHT EQU $36
	; $18
DEF ROUTE_13 EQU $18
DEF ROUTE_13_WIDTH EQU $1E
DEF ROUTE_13_HEIGHT EQU 9
	; $19
DEF ROUTE_14 EQU $19
DEF ROUTE_14_WIDTH EQU $A
DEF ROUTE_14_HEIGHT EQU $1B
	; $1A
DEF ROUTE_15 EQU $1A
DEF ROUTE_15_WIDTH EQU $1E
DEF ROUTE_15_HEIGHT EQU 9
	; $1B
DEF ROUTE_16 EQU $1B
DEF ROUTE_16_WIDTH EQU $14
DEF ROUTE_16_HEIGHT EQU 9
	; $1C
DEF ROUTE_17 EQU $1C
DEF ROUTE_17_WIDTH EQU $A
DEF ROUTE_17_HEIGHT EQU $48
	; $1D
DEF ROUTE_18 EQU $1D
DEF ROUTE_18_WIDTH EQU $19
DEF ROUTE_18_HEIGHT EQU 9
	; $1E
DEF ROUTE_19 EQU $1E
DEF ROUTE_19_WIDTH EQU $A
DEF ROUTE_19_HEIGHT EQU $1B
	; $1F
DEF ROUTE_20 EQU $1F
DEF ROUTE_20_WIDTH EQU $32
DEF ROUTE_20_HEIGHT EQU 9
	; $20
DEF ROUTE_21 EQU $20
DEF ROUTE_21_WIDTH EQU $A
DEF ROUTE_21_HEIGHT EQU $2D
	; $21
DEF ROUTE_22 EQU $21
DEF ROUTE_22_WIDTH EQU $14
DEF ROUTE_22_HEIGHT EQU 9
	; $22
DEF ROUTE_23 EQU $22
DEF ROUTE_23_WIDTH EQU $A
DEF ROUTE_23_HEIGHT EQU $48
	; $23
DEF ROUTE_24 EQU $23
DEF ROUTE_24_WIDTH EQU $A
DEF ROUTE_24_HEIGHT EQU $12
	; $24
DEF ROUTE_25 EQU $24
DEF ROUTE_25_WIDTH EQU $1E
DEF ROUTE_25_HEIGHT EQU 9

DEF FIRST_INDOOR_MAP EQU $25
	; $25
DEF REDS_HOUSE_1F EQU $25
DEF REDS_HOUSE_1F_WIDTH EQU 4
DEF REDS_HOUSE_1F_HEIGHT EQU 4
	; $26
DEF REDS_HOUSE_2F EQU $26
DEF REDS_HOUSE_2F_WIDTH EQU 4
DEF REDS_HOUSE_2F_HEIGHT EQU 4
	; $27
DEF BLUES_HOUSE EQU $27
DEF BLUES_HOUSE_WIDTH EQU 4
DEF BLUES_HOUSE_HEIGHT EQU 4
	; $28
DEF OAKS_LAB EQU $28
DEF OAKS_LAB_WIDTH EQU 5
DEF OAKS_LAB_HEIGHT EQU 6
DEF INDOORGROUP_PALLET_TOWN EQU $29

	; $29
DEF VIRIDIAN_POKECENTER EQU $29
DEF VIRIDIAN_POKECENTER_WIDTH EQU 7
DEF VIRIDIAN_POKECENTER_HEIGHT EQU 4
	; $2A
DEF VIRIDIAN_MART EQU $2A
DEF VIRIDIAN_MART_WIDTH EQU 4
DEF VIRIDIAN_MART_HEIGHT EQU 4
	; $2B
DEF VIRIDIAN_SCHOOL_HOUSE EQU $2B
DEF VIRIDIAN_SCHOOL_HOUSE_WIDTH EQU 4
DEF VIRIDIAN_SCHOOL_HOUSE_HEIGHT EQU 4
	; $2C
DEF VIRIDIAN_NICKNAME_HOUSE EQU $2C
DEF VIRIDIAN_NICKNAME_HOUSE_WIDTH EQU 4
DEF VIRIDIAN_NICKNAME_HOUSE_HEIGHT EQU 4
	; $2D
DEF VIRIDIAN_GYM EQU $2D
DEF VIRIDIAN_GYM_WIDTH EQU $A
DEF VIRIDIAN_GYM_HEIGHT EQU 9
DEF INDOORGROUP_VIRIDIAN_CITY EQU $2E

	; $2E
DEF DIGLETTS_CAVE_ROUTE_2 EQU $2E
DEF DIGLETTS_CAVE_ROUTE_2_WIDTH EQU 4
DEF DIGLETTS_CAVE_ROUTE_2_HEIGHT EQU 4
	; $2F
DEF VIRIDIAN_FOREST_NORTH_GATE EQU $2F
DEF VIRIDIAN_FOREST_NORTH_GATE_WIDTH EQU 5
DEF VIRIDIAN_FOREST_NORTH_GATE_HEIGHT EQU 4
	; $30
DEF ROUTE_2_TRADE_HOUSE EQU $30
DEF ROUTE_2_TRADE_HOUSE_WIDTH EQU 4
DEF ROUTE_2_TRADE_HOUSE_HEIGHT EQU 4
	; $31
DEF ROUTE_2_GATE EQU $31
DEF ROUTE_2_GATE_WIDTH EQU 5
DEF ROUTE_2_GATE_HEIGHT EQU 4
	; $32
DEF VIRIDIAN_FOREST_SOUTH_GATE EQU $32
DEF VIRIDIAN_FOREST_SOUTH_GATE_WIDTH EQU 5
DEF VIRIDIAN_FOREST_SOUTH_GATE_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_2 EQU $33

	; $33
DEF VIRIDIAN_FOREST EQU $33
DEF VIRIDIAN_FOREST_WIDTH EQU $11
DEF VIRIDIAN_FOREST_HEIGHT EQU $18
DEF INDOORGROUP_VIRIDIAN_FOREST EQU $34

	; $34
DEF MUSEUM_1F EQU $34
DEF MUSEUM_1F_WIDTH EQU $A
DEF MUSEUM_1F_HEIGHT EQU 4
	; $35
DEF MUSEUM_2F EQU $35
DEF MUSEUM_2F_WIDTH EQU 7
DEF MUSEUM_2F_HEIGHT EQU 4
	; $36
DEF PEWTER_GYM EQU $36
DEF PEWTER_GYM_WIDTH EQU 5
DEF PEWTER_GYM_HEIGHT EQU 7
	; $37
DEF PEWTER_NIDORAN_HOUSE EQU $37
DEF PEWTER_NIDORAN_HOUSE_WIDTH EQU 4
DEF PEWTER_NIDORAN_HOUSE_HEIGHT EQU 4
	; $38
DEF PEWTER_MART EQU $38
DEF PEWTER_MART_WIDTH EQU 4
DEF PEWTER_MART_HEIGHT EQU 4
	; $39
DEF PEWTER_SPEECH_HOUSE EQU $39
DEF PEWTER_SPEECH_HOUSE_WIDTH EQU 4
DEF PEWTER_SPEECH_HOUSE_HEIGHT EQU 4
	; $3A
DEF PEWTER_POKECENTER EQU $3A
DEF PEWTER_POKECENTER_WIDTH EQU 7
DEF PEWTER_POKECENTER_HEIGHT EQU 4
DEF INDOORGROUP_PEWTER_CITY EQU $3B

	; $3B
DEF MT_MOON_1F EQU $3B
DEF MT_MOON_1F_WIDTH EQU $14
DEF MT_MOON_1F_HEIGHT EQU $12
	; $3C
DEF MT_MOON_B1F EQU $3C
DEF MT_MOON_B1F_WIDTH EQU $E
DEF MT_MOON_B1F_HEIGHT EQU $E
	; $3D
DEF MT_MOON_B2F EQU $3D
DEF MT_MOON_B2F_WIDTH EQU $14
DEF MT_MOON_B2F_HEIGHT EQU $12
DEF INDOORGROUP_MT_MOON EQU $3E

	; $3E
DEF CERULEAN_TRASHED_HOUSE EQU $3E
DEF CERULEAN_TRASHED_HOUSE_WIDTH EQU 4
DEF CERULEAN_TRASHED_HOUSE_HEIGHT EQU 4
	; $3F
DEF CERULEAN_TRADE_HOUSE EQU $3F
DEF CERULEAN_TRADE_HOUSE_WIDTH EQU 4
DEF CERULEAN_TRADE_HOUSE_HEIGHT EQU 4
	; $40
DEF CERULEAN_POKECENTER EQU $40
DEF CERULEAN_POKECENTER_WIDTH EQU 7
DEF CERULEAN_POKECENTER_HEIGHT EQU 4
	; $41
DEF CERULEAN_GYM EQU $41
DEF CERULEAN_GYM_WIDTH EQU 5
DEF CERULEAN_GYM_HEIGHT EQU 7
	; $42
DEF BIKE_SHOP EQU $42
DEF BIKE_SHOP_WIDTH EQU 4
DEF BIKE_SHOP_HEIGHT EQU 4
	; $43
DEF CERULEAN_MART EQU $43
DEF CERULEAN_MART_WIDTH EQU 4
DEF CERULEAN_MART_HEIGHT EQU 4
DEF INDOORGROUP_CERULEAN_CITY EQU $44

	; $44
DEF MT_MOON_POKECENTER EQU $44
DEF MT_MOON_POKECENTER_WIDTH EQU 7
DEF MT_MOON_POKECENTER_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_4 EQU $45

	; $45
DEF CERULEAN_TRASHED_HOUSE_COPY EQU $45
DEF CERULEAN_TRASHED_HOUSE_COPY_WIDTH EQU 4
DEF CERULEAN_TRASHED_HOUSE_COPY_HEIGHT EQU 4
DEF INDOORGROUP_CERULEAN_CITY_2 EQU $46

	; $46
DEF ROUTE_5_GATE EQU $46
DEF ROUTE_5_GATE_WIDTH EQU 4
DEF ROUTE_5_GATE_HEIGHT EQU 3
	; $47
DEF UNDERGROUND_PATH_ROUTE_5 EQU $47
DEF UNDERGROUND_PATH_ROUTE_5_WIDTH EQU 4
DEF UNDERGROUND_PATH_ROUTE_5_HEIGHT EQU 4
	; $48
DEF DAYCARE EQU $48
DEF DAYCARE_WIDTH EQU 4
DEF DAYCARE_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_5 EQU $49

	; $49
DEF ROUTE_6_GATE EQU $49
DEF ROUTE_6_GATE_WIDTH EQU 4
DEF ROUTE_6_GATE_HEIGHT EQU 3
	; $4A
DEF UNDERGROUND_PATH_ROUTE_6 EQU $4A
DEF UNDERGROUND_PATH_ROUTE_6_WIDTH EQU 4
DEF UNDERGROUND_PATH_ROUTE_6_HEIGHT EQU 4
	; $4B
DEF UNDERGROUND_PATH_ROUTE_6_COPY EQU $4B
DEF UNDERGROUND_PATH_ROUTE_6_COPY_WIDTH EQU 4
DEF UNDERGROUND_PATH_ROUTE_6_COPY_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_6 EQU $4C

	; $4C
DEF ROUTE_7_GATE EQU $4C
DEF ROUTE_7_GATE_WIDTH EQU 3
DEF ROUTE_7_GATE_HEIGHT EQU 4
	; $4D
DEF UNDERGROUND_PATH_ROUTE_7 EQU $4D
DEF UNDERGROUND_PATH_ROUTE_7_WIDTH EQU 4
DEF UNDERGROUND_PATH_ROUTE_7_HEIGHT EQU 4
	; $4E
DEF UNDERGROUND_PATH_ROUTE_7_COPY EQU $4E
DEF UNDERGROUND_PATH_ROUTE_7_COPY_WIDTH EQU 4
DEF UNDERGROUND_PATH_ROUTE_7_COPY_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_7 EQU $4F

	; $4F
DEF ROUTE_8_GATE EQU $4F
DEF ROUTE_8_GATE_WIDTH EQU 3
DEF ROUTE_8_GATE_HEIGHT EQU 4
	; $50
DEF UNDERGROUND_PATH_ROUTE_8 EQU $50
DEF UNDERGROUND_PATH_ROUTE_8_WIDTH EQU 4
DEF UNDERGROUND_PATH_ROUTE_8_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_8 EQU $51

	; $51
DEF ROCK_TUNNEL_POKECENTER EQU $51
DEF ROCK_TUNNEL_POKECENTER_WIDTH EQU 7
DEF ROCK_TUNNEL_POKECENTER_HEIGHT EQU 4
	; $52
DEF ROCK_TUNNEL_1F EQU $52
DEF ROCK_TUNNEL_1F_WIDTH EQU $14
DEF ROCK_TUNNEL_1F_HEIGHT EQU $12
DEF INDOORGROUP_ROCK_TUNNEL EQU $53

	; $53
DEF POWER_PLANT EQU $53
DEF POWER_PLANT_WIDTH EQU $14
DEF POWER_PLANT_HEIGHT EQU $12
DEF INDOORGROUP_POWER_PLANT EQU $54

	; $54
DEF ROUTE_11_GATE_1F EQU $54
DEF ROUTE_11_GATE_1F_WIDTH EQU 4
DEF ROUTE_11_GATE_1F_HEIGHT EQU 5
	; $55
DEF DIGLETTS_CAVE_ROUTE_11 EQU $55
DEF DIGLETTS_CAVE_ROUTE_11_WIDTH EQU 4
DEF DIGLETTS_CAVE_ROUTE_11_HEIGHT EQU 4
	; $56
DEF ROUTE_11_GATE_2F EQU $56
DEF ROUTE_11_GATE_2F_WIDTH EQU 4
DEF ROUTE_11_GATE_2F_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_11 EQU $57

	; $57
DEF ROUTE_12_GATE_1F EQU $57
DEF ROUTE_12_GATE_1F_WIDTH EQU 5
DEF ROUTE_12_GATE_1F_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_12 EQU $58

	; $58
DEF BILLS_HOUSE EQU $58
DEF BILLS_HOUSE_WIDTH EQU 4
DEF BILLS_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_SEA_COTTAGE EQU $59

	; $59
DEF VERMILION_POKECENTER EQU $59
DEF VERMILION_POKECENTER_WIDTH EQU 7
DEF VERMILION_POKECENTER_HEIGHT EQU 4
	; $5A
DEF POKEMON_FAN_CLUB EQU $5A
DEF POKEMON_FAN_CLUB_WIDTH EQU 4
DEF POKEMON_FAN_CLUB_HEIGHT EQU 4
	; $5B
DEF VERMILION_MART EQU $5B
DEF VERMILION_MART_WIDTH EQU 4
DEF VERMILION_MART_HEIGHT EQU 4
	; $5C
DEF VERMILION_GYM EQU $5C
DEF VERMILION_GYM_WIDTH EQU 5
DEF VERMILION_GYM_HEIGHT EQU 9
	; $5D
DEF VERMILION_PIDGEY_HOUSE EQU $5D
DEF VERMILION_PIDGEY_HOUSE_WIDTH EQU 4
DEF VERMILION_PIDGEY_HOUSE_HEIGHT EQU 4
	; $5E
DEF VERMILION_DOCK EQU $5E
DEF VERMILION_DOCK_WIDTH EQU $E
DEF VERMILION_DOCK_HEIGHT EQU 6
DEF INDOORGROUP_VERMILION_CITY EQU $5F

	; $5F
DEF SS_ANNE_1F EQU $5F
DEF SS_ANNE_1F_WIDTH EQU $14
DEF SS_ANNE_1F_HEIGHT EQU 9
	; $60
DEF SS_ANNE_2F EQU $60
DEF SS_ANNE_2F_WIDTH EQU $14
DEF SS_ANNE_2F_HEIGHT EQU 9
	; $61
DEF SS_ANNE_3F EQU $61
DEF SS_ANNE_3F_WIDTH EQU $A
DEF SS_ANNE_3F_HEIGHT EQU 3
	; $62
DEF SS_ANNE_B1F EQU $62
DEF SS_ANNE_B1F_WIDTH EQU $F
DEF SS_ANNE_B1F_HEIGHT EQU 4
	; $63
DEF SS_ANNE_BOW EQU $63
DEF SS_ANNE_BOW_WIDTH EQU $A
DEF SS_ANNE_BOW_HEIGHT EQU 7
	; $64
DEF SS_ANNE_KITCHEN EQU $64
DEF SS_ANNE_KITCHEN_WIDTH EQU 7
DEF SS_ANNE_KITCHEN_HEIGHT EQU 8
	; $65
DEF SS_ANNE_CAPTAINS_ROOM EQU $65
DEF SS_ANNE_CAPTAINS_ROOM_WIDTH EQU 3
DEF SS_ANNE_CAPTAINS_ROOM_HEIGHT EQU 4
	; $66
DEF SS_ANNE_1F_ROOMS EQU $66
DEF SS_ANNE_1F_ROOMS_WIDTH EQU $C
DEF SS_ANNE_1F_ROOMS_HEIGHT EQU 8
	; $67
DEF SS_ANNE_2F_ROOMS EQU $67
DEF SS_ANNE_2F_ROOMS_WIDTH EQU $C
DEF SS_ANNE_2F_ROOMS_HEIGHT EQU 8
	; $68
DEF SS_ANNE_B1F_ROOMS EQU $68
DEF SS_ANNE_B1F_ROOMS_WIDTH EQU $C
DEF SS_ANNE_B1F_ROOMS_HEIGHT EQU 8
DEF INDOORGROUP_SS_ANNE EQU $69

	; $69
DEF UNUSED_MAP_69 EQU $69
DEF UNUSED_MAP_69_WIDTH EQU 0
DEF UNUSED_MAP_69_HEIGHT EQU 0
	; $6A
DEF UNUSED_MAP_6A EQU $6A
DEF UNUSED_MAP_6A_WIDTH EQU 0
DEF UNUSED_MAP_6A_HEIGHT EQU 0
	; $6B
DEF UNUSED_MAP_6B EQU $6B
DEF UNUSED_MAP_6B_WIDTH EQU 0
DEF UNUSED_MAP_6B_HEIGHT EQU 0
	; $6C
DEF VICTORY_ROAD_1F EQU $6C
DEF VICTORY_ROAD_1F_WIDTH EQU $A
DEF VICTORY_ROAD_1F_HEIGHT EQU 9
DEF INDOORGROUP_VICTORY_ROAD EQU $6D

	; $6D
DEF UNUSED_MAP_6D EQU $6D
DEF UNUSED_MAP_6D_WIDTH EQU 0
DEF UNUSED_MAP_6D_HEIGHT EQU 0
	; $6E
DEF UNUSED_MAP_6E EQU $6E
DEF UNUSED_MAP_6E_WIDTH EQU 0
DEF UNUSED_MAP_6E_HEIGHT EQU 0
	; $6F
DEF UNUSED_MAP_6F EQU $6F
DEF UNUSED_MAP_6F_WIDTH EQU 0
DEF UNUSED_MAP_6F_HEIGHT EQU 0
	; $70
DEF UNUSED_MAP_70 EQU $70
DEF UNUSED_MAP_70_WIDTH EQU 0
DEF UNUSED_MAP_70_HEIGHT EQU 0
	; $71
DEF LANCES_ROOM EQU $71
DEF LANCES_ROOM_WIDTH EQU $D
DEF LANCES_ROOM_HEIGHT EQU $D
	; $72
DEF UNUSED_MAP_72 EQU $72
DEF UNUSED_MAP_72_WIDTH EQU 0
DEF UNUSED_MAP_72_HEIGHT EQU 0
	; $73
DEF UNUSED_MAP_73 EQU $73
DEF UNUSED_MAP_73_WIDTH EQU 0
DEF UNUSED_MAP_73_HEIGHT EQU 0
	; $74
DEF UNUSED_MAP_74 EQU $74
DEF UNUSED_MAP_74_WIDTH EQU 0
DEF UNUSED_MAP_74_HEIGHT EQU 0
	; $75
DEF UNUSED_MAP_75 EQU $75
DEF UNUSED_MAP_75_WIDTH EQU 0
DEF UNUSED_MAP_75_HEIGHT EQU 0
	; $76
DEF HALL_OF_FAME EQU $76
DEF HALL_OF_FAME_WIDTH EQU 5
DEF HALL_OF_FAME_HEIGHT EQU 4
DEF INDOORGROUP_POKEMON_LEAGUE EQU $77

	; $77 ; UndergroundPathNorthSouth.blk is actually 4x23
DEF UNDERGROUND_PATH_NORTH_SOUTH EQU $77
DEF UNDERGROUND_PATH_NORTH_SOUTH_WIDTH EQU 4
DEF UNDERGROUND_PATH_NORTH_SOUTH_HEIGHT EQU $18
DEF INDOORGROUP_UNDERGROUND_PATH EQU $78

	; $78
DEF CHAMPIONS_ROOM EQU $78
DEF CHAMPIONS_ROOM_WIDTH EQU 4
DEF CHAMPIONS_ROOM_HEIGHT EQU 4
DEF INDOORGROUP_POKEMON_LEAGUE_2 EQU $79

	; $79
DEF UNDERGROUND_PATH_WEST_EAST EQU $79
DEF UNDERGROUND_PATH_WEST_EAST_WIDTH EQU $19
DEF UNDERGROUND_PATH_WEST_EAST_HEIGHT EQU 4
DEF INDOORGROUP_UNDERGROUND_PATH_2 EQU $7A

	; $7A
DEF CELADON_MART_1F EQU $7A
DEF CELADON_MART_1F_WIDTH EQU $A
DEF CELADON_MART_1F_HEIGHT EQU 4
	; $7B
DEF CELADON_MART_2F EQU $7B
DEF CELADON_MART_2F_WIDTH EQU $A
DEF CELADON_MART_2F_HEIGHT EQU 4
	; $7C
DEF CELADON_MART_3F EQU $7C
DEF CELADON_MART_3F_WIDTH EQU $A
DEF CELADON_MART_3F_HEIGHT EQU 4
	; $7D
DEF CELADON_MART_4F EQU $7D
DEF CELADON_MART_4F_WIDTH EQU $A
DEF CELADON_MART_4F_HEIGHT EQU 4
	; $7E
DEF CELADON_MART_ROOF EQU $7E
DEF CELADON_MART_ROOF_WIDTH EQU $A
DEF CELADON_MART_ROOF_HEIGHT EQU 4
	; $7F
DEF CELADON_MART_ELEVATOR EQU $7F
DEF CELADON_MART_ELEVATOR_WIDTH EQU 2
DEF CELADON_MART_ELEVATOR_HEIGHT EQU 2
	; $80
DEF CELADON_MANSION_1F EQU $80
DEF CELADON_MANSION_1F_WIDTH EQU 4
DEF CELADON_MANSION_1F_HEIGHT EQU 6
	; $81
DEF CELADON_MANSION_2F EQU $81
DEF CELADON_MANSION_2F_WIDTH EQU 4
DEF CELADON_MANSION_2F_HEIGHT EQU 6
	; $82
DEF CELADON_MANSION_3F EQU $82
DEF CELADON_MANSION_3F_WIDTH EQU 4
DEF CELADON_MANSION_3F_HEIGHT EQU 6
	; $83
DEF CELADON_MANSION_ROOF EQU $83
DEF CELADON_MANSION_ROOF_WIDTH EQU 4
DEF CELADON_MANSION_ROOF_HEIGHT EQU 6
	; $84
DEF CELADON_MANSION_ROOF_HOUSE EQU $84
DEF CELADON_MANSION_ROOF_HOUSE_WIDTH EQU 4
DEF CELADON_MANSION_ROOF_HOUSE_HEIGHT EQU 4
	; $85
DEF CELADON_POKECENTER EQU $85
DEF CELADON_POKECENTER_WIDTH EQU 7
DEF CELADON_POKECENTER_HEIGHT EQU 4
	; $86
DEF CELADON_GYM EQU $86
DEF CELADON_GYM_WIDTH EQU 5
DEF CELADON_GYM_HEIGHT EQU 9
	; $87
DEF GAME_CORNER EQU $87
DEF GAME_CORNER_WIDTH EQU $A
DEF GAME_CORNER_HEIGHT EQU 9
	; $88
DEF CELADON_MART_5F EQU $88
DEF CELADON_MART_5F_WIDTH EQU $A
DEF CELADON_MART_5F_HEIGHT EQU 4
	; $89
DEF GAME_CORNER_PRIZE_ROOM EQU $89
DEF GAME_CORNER_PRIZE_ROOM_WIDTH EQU 5
DEF GAME_CORNER_PRIZE_ROOM_HEIGHT EQU 4
	; $8A
DEF CELADON_DINER EQU $8A
DEF CELADON_DINER_WIDTH EQU 5
DEF CELADON_DINER_HEIGHT EQU 4
	; $8B
DEF CELADON_CHIEF_HOUSE EQU $8B
DEF CELADON_CHIEF_HOUSE_WIDTH EQU 4
DEF CELADON_CHIEF_HOUSE_HEIGHT EQU 4
	; $8C
DEF CELADON_HOTEL EQU $8C
DEF CELADON_HOTEL_WIDTH EQU 7
DEF CELADON_HOTEL_HEIGHT EQU 4
DEF INDOORGROUP_CELADON_CITY EQU $8D

	; $8D
DEF LAVENDER_POKECENTER EQU $8D
DEF LAVENDER_POKECENTER_WIDTH EQU 7
DEF LAVENDER_POKECENTER_HEIGHT EQU 4
DEF INDOORGROUP_LAVENDER_TOWN EQU $8E

	; $8E
DEF POKEMON_TOWER_1F EQU $8E
DEF POKEMON_TOWER_1F_WIDTH EQU $A
DEF POKEMON_TOWER_1F_HEIGHT EQU 9
	; $8F
DEF POKEMON_TOWER_2F EQU $8F
DEF POKEMON_TOWER_2F_WIDTH EQU $A
DEF POKEMON_TOWER_2F_HEIGHT EQU 9
	; $90
DEF POKEMON_TOWER_3F EQU $90
DEF POKEMON_TOWER_3F_WIDTH EQU $A
DEF POKEMON_TOWER_3F_HEIGHT EQU 9
	; $91
DEF POKEMON_TOWER_4F EQU $91
DEF POKEMON_TOWER_4F_WIDTH EQU $A
DEF POKEMON_TOWER_4F_HEIGHT EQU 9
	; $92
DEF POKEMON_TOWER_5F EQU $92
DEF POKEMON_TOWER_5F_WIDTH EQU $A
DEF POKEMON_TOWER_5F_HEIGHT EQU 9
	; $93
DEF POKEMON_TOWER_6F EQU $93
DEF POKEMON_TOWER_6F_WIDTH EQU $A
DEF POKEMON_TOWER_6F_HEIGHT EQU 9
	; $94
DEF POKEMON_TOWER_7F EQU $94
DEF POKEMON_TOWER_7F_WIDTH EQU $A
DEF POKEMON_TOWER_7F_HEIGHT EQU 9
DEF INDOORGROUP_POKEMON_TOWER EQU $95

	; $95
DEF MR_FUJIS_HOUSE EQU $95
DEF MR_FUJIS_HOUSE_WIDTH EQU 4
DEF MR_FUJIS_HOUSE_HEIGHT EQU 4
	; $96
DEF LAVENDER_MART EQU $96
DEF LAVENDER_MART_WIDTH EQU 4
DEF LAVENDER_MART_HEIGHT EQU 4
	; $97
DEF LAVENDER_CUBONE_HOUSE EQU $97
DEF LAVENDER_CUBONE_HOUSE_WIDTH EQU 4
DEF LAVENDER_CUBONE_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_LAVENDER_TOWN_2 EQU $98

	; $98
DEF FUCHSIA_MART EQU $98
DEF FUCHSIA_MART_WIDTH EQU 4
DEF FUCHSIA_MART_HEIGHT EQU 4
	; $99
DEF FUCHSIA_BILLS_GRANDPAS_HOUSE EQU $99
DEF FUCHSIA_BILLS_GRANDPAS_HOUSE_WIDTH EQU 4
DEF FUCHSIA_BILLS_GRANDPAS_HOUSE_HEIGHT EQU 4
	; $9A
DEF FUCHSIA_POKECENTER EQU $9A
DEF FUCHSIA_POKECENTER_WIDTH EQU 7
DEF FUCHSIA_POKECENTER_HEIGHT EQU 4
	; $9B
DEF WARDENS_HOUSE EQU $9B
DEF WARDENS_HOUSE_WIDTH EQU 5
DEF WARDENS_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_FUCHSIA_CITY EQU $9C

	; $9C
DEF SAFARI_ZONE_GATE EQU $9C
DEF SAFARI_ZONE_GATE_WIDTH EQU 4
DEF SAFARI_ZONE_GATE_HEIGHT EQU 3
DEF INDOORGROUP_SAFARI_ZONE EQU $9D

	; $9D
DEF FUCHSIA_GYM EQU $9D
DEF FUCHSIA_GYM_WIDTH EQU 5
DEF FUCHSIA_GYM_HEIGHT EQU 9
	; $9E
DEF FUCHSIA_MEETING_ROOM EQU $9E
DEF FUCHSIA_MEETING_ROOM_WIDTH EQU 7
DEF FUCHSIA_MEETING_ROOM_HEIGHT EQU 4
DEF INDOORGROUP_FUCHSIA_CITY_2 EQU $9F

	; $9F
DEF SEAFOAM_ISLANDS_B1F EQU $9F
DEF SEAFOAM_ISLANDS_B1F_WIDTH EQU $F
DEF SEAFOAM_ISLANDS_B1F_HEIGHT EQU 9
	; $A0
DEF SEAFOAM_ISLANDS_B2F EQU $A0
DEF SEAFOAM_ISLANDS_B2F_WIDTH EQU $F
DEF SEAFOAM_ISLANDS_B2F_HEIGHT EQU 9
	; $A1
DEF SEAFOAM_ISLANDS_B3F EQU $A1
DEF SEAFOAM_ISLANDS_B3F_WIDTH EQU $F
DEF SEAFOAM_ISLANDS_B3F_HEIGHT EQU 9
	; $A2
DEF SEAFOAM_ISLANDS_B4F EQU $A2
DEF SEAFOAM_ISLANDS_B4F_WIDTH EQU $F
DEF SEAFOAM_ISLANDS_B4F_HEIGHT EQU 9
DEF INDOORGROUP_SEAFOAM_ISLANDS EQU $A3

	; $A3
DEF VERMILION_OLD_ROD_HOUSE EQU $A3
DEF VERMILION_OLD_ROD_HOUSE_WIDTH EQU 4
DEF VERMILION_OLD_ROD_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_VERMILION_CITY_2 EQU $A4

	; $A4
DEF FUCHSIA_GOOD_ROD_HOUSE EQU $A4
DEF FUCHSIA_GOOD_ROD_HOUSE_WIDTH EQU 4
DEF FUCHSIA_GOOD_ROD_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_FUCHSIA_CITY_3 EQU $A5

	; $A5
DEF POKEMON_MANSION_1F EQU $A5
DEF POKEMON_MANSION_1F_WIDTH EQU $F
DEF POKEMON_MANSION_1F_HEIGHT EQU $E
DEF INDOORGROUP_POKEMON_MANSION EQU $A6

	; $A6
DEF CINNABAR_GYM EQU $A6
DEF CINNABAR_GYM_WIDTH EQU $A
DEF CINNABAR_GYM_HEIGHT EQU 9
	; $A7
DEF CINNABAR_LAB EQU $A7
DEF CINNABAR_LAB_WIDTH EQU 9
DEF CINNABAR_LAB_HEIGHT EQU 4
	; $A8
DEF CINNABAR_LAB_TRADE_ROOM EQU $A8
DEF CINNABAR_LAB_TRADE_ROOM_WIDTH EQU 4
DEF CINNABAR_LAB_TRADE_ROOM_HEIGHT EQU 4
	; $A9
DEF CINNABAR_LAB_METRONOME_ROOM EQU $A9
DEF CINNABAR_LAB_METRONOME_ROOM_WIDTH EQU 4
DEF CINNABAR_LAB_METRONOME_ROOM_HEIGHT EQU 4
	; $AA
DEF CINNABAR_LAB_FOSSIL_ROOM EQU $AA
DEF CINNABAR_LAB_FOSSIL_ROOM_WIDTH EQU 4
DEF CINNABAR_LAB_FOSSIL_ROOM_HEIGHT EQU 4
	; $AB
DEF CINNABAR_POKECENTER EQU $AB
DEF CINNABAR_POKECENTER_WIDTH EQU 7
DEF CINNABAR_POKECENTER_HEIGHT EQU 4
	; $AC
DEF CINNABAR_MART EQU $AC
DEF CINNABAR_MART_WIDTH EQU 4
DEF CINNABAR_MART_HEIGHT EQU 4
	; $AD
DEF CINNABAR_MART_COPY EQU $AD
DEF CINNABAR_MART_COPY_WIDTH EQU 4
DEF CINNABAR_MART_COPY_HEIGHT EQU 4
DEF INDOORGROUP_CINNABAR_ISLAND EQU $AE

	; $AE
DEF INDIGO_PLATEAU_LOBBY EQU $AE
DEF INDIGO_PLATEAU_LOBBY_WIDTH EQU 8
DEF INDIGO_PLATEAU_LOBBY_HEIGHT EQU 6
DEF INDOORGROUP_INDIGO_PLATEAU EQU $AF

	; $AF
DEF COPYCATS_HOUSE_1F EQU $AF
DEF COPYCATS_HOUSE_1F_WIDTH EQU 4
DEF COPYCATS_HOUSE_1F_HEIGHT EQU 4
	; $B0
DEF COPYCATS_HOUSE_2F EQU $B0
DEF COPYCATS_HOUSE_2F_WIDTH EQU 4
DEF COPYCATS_HOUSE_2F_HEIGHT EQU 4
	; $B1
DEF FIGHTING_DOJO EQU $B1
DEF FIGHTING_DOJO_WIDTH EQU 5
DEF FIGHTING_DOJO_HEIGHT EQU 6
	; $B2
DEF SAFFRON_GYM EQU $B2
DEF SAFFRON_GYM_WIDTH EQU $A
DEF SAFFRON_GYM_HEIGHT EQU 9
	; $B3
DEF SAFFRON_PIDGEY_HOUSE EQU $B3
DEF SAFFRON_PIDGEY_HOUSE_WIDTH EQU 4
DEF SAFFRON_PIDGEY_HOUSE_HEIGHT EQU 4
	; $B4
DEF SAFFRON_MART EQU $B4
DEF SAFFRON_MART_WIDTH EQU 4
DEF SAFFRON_MART_HEIGHT EQU 4
	; $B5
DEF SILPH_CO_1F EQU $B5
DEF SILPH_CO_1F_WIDTH EQU $F
DEF SILPH_CO_1F_HEIGHT EQU 9
	; $B6
DEF SAFFRON_POKECENTER EQU $B6
DEF SAFFRON_POKECENTER_WIDTH EQU 7
DEF SAFFRON_POKECENTER_HEIGHT EQU 4
	; $B7
DEF MR_PSYCHICS_HOUSE EQU $B7
DEF MR_PSYCHICS_HOUSE_WIDTH EQU 4
DEF MR_PSYCHICS_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_SAFFRON_CITY EQU $B8

	; $B8
DEF ROUTE_15_GATE_1F EQU $B8
DEF ROUTE_15_GATE_1F_WIDTH EQU 4
DEF ROUTE_15_GATE_1F_HEIGHT EQU 5
	; $B9
DEF ROUTE_15_GATE_2F EQU $B9
DEF ROUTE_15_GATE_2F_WIDTH EQU 4
DEF ROUTE_15_GATE_2F_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_15 EQU $BA

	; $BA
DEF ROUTE_16_GATE_1F EQU $BA
DEF ROUTE_16_GATE_1F_WIDTH EQU 4
DEF ROUTE_16_GATE_1F_HEIGHT EQU 7
	; $BB
DEF ROUTE_16_GATE_2F EQU $BB
DEF ROUTE_16_GATE_2F_WIDTH EQU 4
DEF ROUTE_16_GATE_2F_HEIGHT EQU 4
	; $BC
DEF ROUTE_16_FLY_HOUSE EQU $BC
DEF ROUTE_16_FLY_HOUSE_WIDTH EQU 4
DEF ROUTE_16_FLY_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_16 EQU $BD

	; $BD
DEF ROUTE_12_SUPER_ROD_HOUSE EQU $BD
DEF ROUTE_12_SUPER_ROD_HOUSE_WIDTH EQU 4
DEF ROUTE_12_SUPER_ROD_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_12_2 EQU $BE

	; $BE
DEF ROUTE_18_GATE_1F EQU $BE
DEF ROUTE_18_GATE_1F_WIDTH EQU 4
DEF ROUTE_18_GATE_1F_HEIGHT EQU 5
	; $BF
DEF ROUTE_18_GATE_2F EQU $BF
DEF ROUTE_18_GATE_2F_WIDTH EQU 4
DEF ROUTE_18_GATE_2F_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_18 EQU $C0

	; $C0
DEF SEAFOAM_ISLANDS_1F EQU $C0
DEF SEAFOAM_ISLANDS_1F_WIDTH EQU $F
DEF SEAFOAM_ISLANDS_1F_HEIGHT EQU 9
DEF INDOORGROUP_SEAFOAM_ISLANDS_2 EQU $C1

	; $C1
DEF ROUTE_22_GATE EQU $C1
DEF ROUTE_22_GATE_WIDTH EQU 5
DEF ROUTE_22_GATE_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_22 EQU $C2

	; $C2
DEF VICTORY_ROAD_2F EQU $C2
DEF VICTORY_ROAD_2F_WIDTH EQU $F
DEF VICTORY_ROAD_2F_HEIGHT EQU 9
DEF INDOORGROUP_VICTORY_ROAD_2 EQU $C3

	; $C3
DEF ROUTE_12_GATE_2F EQU $C3
DEF ROUTE_12_GATE_2F_WIDTH EQU 4
DEF ROUTE_12_GATE_2F_HEIGHT EQU 4
DEF INDOORGROUP_ROUTE_12_3 EQU $C4

	; $C4
DEF VERMILION_TRADE_HOUSE EQU $C4
DEF VERMILION_TRADE_HOUSE_WIDTH EQU 4
DEF VERMILION_TRADE_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_VERMILION_CITY_3 EQU $C5

	; $C5
DEF DIGLETTS_CAVE EQU $C5
DEF DIGLETTS_CAVE_WIDTH EQU $14
DEF DIGLETTS_CAVE_HEIGHT EQU $12
DEF INDOORGROUP_DIGLETTS_CAVE EQU $C6

	; $C6
DEF VICTORY_ROAD_3F EQU $C6
DEF VICTORY_ROAD_3F_WIDTH EQU $F
DEF VICTORY_ROAD_3F_HEIGHT EQU 9
DEF INDOORGROUP_VICTORY_ROAD_3 EQU $C7

	; $C7
DEF ROCKET_HIDEOUT_B1F EQU $C7
DEF ROCKET_HIDEOUT_B1F_WIDTH EQU $F
DEF ROCKET_HIDEOUT_B1F_HEIGHT EQU $E
	; $C8
DEF ROCKET_HIDEOUT_B2F EQU $C8
DEF ROCKET_HIDEOUT_B2F_WIDTH EQU $F
DEF ROCKET_HIDEOUT_B2F_HEIGHT EQU $E
	; $C9
DEF ROCKET_HIDEOUT_B3F EQU $C9
DEF ROCKET_HIDEOUT_B3F_WIDTH EQU $F
DEF ROCKET_HIDEOUT_B3F_HEIGHT EQU $E
	; $CA
DEF ROCKET_HIDEOUT_B4F EQU $CA
DEF ROCKET_HIDEOUT_B4F_WIDTH EQU $F
DEF ROCKET_HIDEOUT_B4F_HEIGHT EQU $C
	; $CB
DEF ROCKET_HIDEOUT_ELEVATOR EQU $CB
DEF ROCKET_HIDEOUT_ELEVATOR_WIDTH EQU 3
DEF ROCKET_HIDEOUT_ELEVATOR_HEIGHT EQU 4
	; $CC
DEF UNUSED_MAP_CC EQU $CC
DEF UNUSED_MAP_CC_WIDTH EQU 0
DEF UNUSED_MAP_CC_HEIGHT EQU 0
	; $CD
DEF UNUSED_MAP_CD EQU $CD
DEF UNUSED_MAP_CD_WIDTH EQU 0
DEF UNUSED_MAP_CD_HEIGHT EQU 0
	; $CE
DEF UNUSED_MAP_CE EQU $CE
DEF UNUSED_MAP_CE_WIDTH EQU 0
DEF UNUSED_MAP_CE_HEIGHT EQU 0
DEF INDOORGROUP_ROCKET_HQ EQU $CF

	; $CF
DEF SILPH_CO_2F EQU $CF
DEF SILPH_CO_2F_WIDTH EQU $F
DEF SILPH_CO_2F_HEIGHT EQU 9
	; $D0
DEF SILPH_CO_3F EQU $D0
DEF SILPH_CO_3F_WIDTH EQU $F
DEF SILPH_CO_3F_HEIGHT EQU 9
	; $D1
DEF SILPH_CO_4F EQU $D1
DEF SILPH_CO_4F_WIDTH EQU $F
DEF SILPH_CO_4F_HEIGHT EQU 9
	; $D2
DEF SILPH_CO_5F EQU $D2
DEF SILPH_CO_5F_WIDTH EQU $F
DEF SILPH_CO_5F_HEIGHT EQU 9
	; $D3
DEF SILPH_CO_6F EQU $D3
DEF SILPH_CO_6F_WIDTH EQU $D
DEF SILPH_CO_6F_HEIGHT EQU 9
	; $D4
DEF SILPH_CO_7F EQU $D4
DEF SILPH_CO_7F_WIDTH EQU $D
DEF SILPH_CO_7F_HEIGHT EQU 9
	; $D5
DEF SILPH_CO_8F EQU $D5
DEF SILPH_CO_8F_WIDTH EQU $D
DEF SILPH_CO_8F_HEIGHT EQU 9
DEF INDOORGROUP_SILPH_CO EQU $D6

	; $D6
DEF POKEMON_MANSION_2F EQU $D6
DEF POKEMON_MANSION_2F_WIDTH EQU $F
DEF POKEMON_MANSION_2F_HEIGHT EQU $E
	; $D7
DEF POKEMON_MANSION_3F EQU $D7
DEF POKEMON_MANSION_3F_WIDTH EQU $F
DEF POKEMON_MANSION_3F_HEIGHT EQU 9
	; $D8
DEF POKEMON_MANSION_B1F EQU $D8
DEF POKEMON_MANSION_B1F_WIDTH EQU $F
DEF POKEMON_MANSION_B1F_HEIGHT EQU $E
DEF INDOORGROUP_POKEMON_MANSION_2 EQU $D9

	; $D9
DEF SAFARI_ZONE_EAST EQU $D9
DEF SAFARI_ZONE_EAST_WIDTH EQU $F
DEF SAFARI_ZONE_EAST_HEIGHT EQU $D
	; $DA
DEF SAFARI_ZONE_NORTH EQU $DA
DEF SAFARI_ZONE_NORTH_WIDTH EQU $14
DEF SAFARI_ZONE_NORTH_HEIGHT EQU $12
	; $DB
DEF SAFARI_ZONE_WEST EQU $DB
DEF SAFARI_ZONE_WEST_WIDTH EQU $F
DEF SAFARI_ZONE_WEST_HEIGHT EQU $D
	; $DC
DEF SAFARI_ZONE_CENTER EQU $DC
DEF SAFARI_ZONE_CENTER_WIDTH EQU $F
DEF SAFARI_ZONE_CENTER_HEIGHT EQU $D
	; $DD
DEF SAFARI_ZONE_CENTER_REST_HOUSE EQU $DD
DEF SAFARI_ZONE_CENTER_REST_HOUSE_WIDTH EQU 4
DEF SAFARI_ZONE_CENTER_REST_HOUSE_HEIGHT EQU 4
	; $DE
DEF SAFARI_ZONE_SECRET_HOUSE EQU $DE
DEF SAFARI_ZONE_SECRET_HOUSE_WIDTH EQU 4
DEF SAFARI_ZONE_SECRET_HOUSE_HEIGHT EQU 4
	; $DF
DEF SAFARI_ZONE_WEST_REST_HOUSE EQU $DF
DEF SAFARI_ZONE_WEST_REST_HOUSE_WIDTH EQU 4
DEF SAFARI_ZONE_WEST_REST_HOUSE_HEIGHT EQU 4
	; $E0
DEF SAFARI_ZONE_EAST_REST_HOUSE EQU $E0
DEF SAFARI_ZONE_EAST_REST_HOUSE_WIDTH EQU 4
DEF SAFARI_ZONE_EAST_REST_HOUSE_HEIGHT EQU 4
	; $E1
DEF SAFARI_ZONE_NORTH_REST_HOUSE EQU $E1
DEF SAFARI_ZONE_NORTH_REST_HOUSE_WIDTH EQU 4
DEF SAFARI_ZONE_NORTH_REST_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_SAFARI_ZONE_2 EQU $E2

	; $E2
DEF CERULEAN_CAVE_2F EQU $E2
DEF CERULEAN_CAVE_2F_WIDTH EQU $F
DEF CERULEAN_CAVE_2F_HEIGHT EQU 9
	; $E3
DEF CERULEAN_CAVE_B1F EQU $E3
DEF CERULEAN_CAVE_B1F_WIDTH EQU $F
DEF CERULEAN_CAVE_B1F_HEIGHT EQU 9
	; $E4
DEF CERULEAN_CAVE_1F EQU $E4
DEF CERULEAN_CAVE_1F_WIDTH EQU $F
DEF CERULEAN_CAVE_1F_HEIGHT EQU 9
DEF INDOORGROUP_CERULEAN_CAVE EQU $E5

	; $E5
DEF NAME_RATERS_HOUSE EQU $E5
DEF NAME_RATERS_HOUSE_WIDTH EQU 4
DEF NAME_RATERS_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_LAVENDER_TOWN_3 EQU $E6

	; $E6
DEF CERULEAN_BADGE_HOUSE EQU $E6
DEF CERULEAN_BADGE_HOUSE_WIDTH EQU 4
DEF CERULEAN_BADGE_HOUSE_HEIGHT EQU 4
DEF INDOORGROUP_CERULEAN_CITY_3 EQU $E7

	; $E7
DEF UNUSED_MAP_E7 EQU $E7
DEF UNUSED_MAP_E7_WIDTH EQU 0
DEF UNUSED_MAP_E7_HEIGHT EQU 0
	; $E8
DEF ROCK_TUNNEL_B1F EQU $E8
DEF ROCK_TUNNEL_B1F_WIDTH EQU $14
DEF ROCK_TUNNEL_B1F_HEIGHT EQU $12
DEF INDOORGROUP_ROCK_TUNNEL_2 EQU $E9

	; $E9
DEF SILPH_CO_9F EQU $E9
DEF SILPH_CO_9F_WIDTH EQU $D
DEF SILPH_CO_9F_HEIGHT EQU 9
	; $EA
DEF SILPH_CO_10F EQU $EA
DEF SILPH_CO_10F_WIDTH EQU 8
DEF SILPH_CO_10F_HEIGHT EQU 9
	; $EB
DEF SILPH_CO_11F EQU $EB
DEF SILPH_CO_11F_WIDTH EQU 9
DEF SILPH_CO_11F_HEIGHT EQU 9
	; $EC
DEF SILPH_CO_ELEVATOR EQU $EC
DEF SILPH_CO_ELEVATOR_WIDTH EQU 2
DEF SILPH_CO_ELEVATOR_HEIGHT EQU 2
DEF INDOORGROUP_SILPH_CO_2 EQU $ED

	; $ED
DEF UNUSED_MAP_ED EQU $ED
DEF UNUSED_MAP_ED_WIDTH EQU 0
DEF UNUSED_MAP_ED_HEIGHT EQU 0
	; $EE
DEF UNUSED_MAP_EE EQU $EE
DEF UNUSED_MAP_EE_WIDTH EQU 0
DEF UNUSED_MAP_EE_HEIGHT EQU 0
	; $EF
DEF TRADE_CENTER EQU $EF
DEF TRADE_CENTER_WIDTH EQU 5
DEF TRADE_CENTER_HEIGHT EQU 4
	; $F0
DEF COLOSSEUM EQU $F0
DEF COLOSSEUM_WIDTH EQU 5
DEF COLOSSEUM_HEIGHT EQU 4
	; $F1
DEF UNUSED_MAP_F1 EQU $F1
DEF UNUSED_MAP_F1_WIDTH EQU 0
DEF UNUSED_MAP_F1_HEIGHT EQU 0
	; $F2
DEF UNUSED_MAP_F2 EQU $F2
DEF UNUSED_MAP_F2_WIDTH EQU 0
DEF UNUSED_MAP_F2_HEIGHT EQU 0
	; $F3
DEF UNUSED_MAP_F3 EQU $F3
DEF UNUSED_MAP_F3_WIDTH EQU 0
DEF UNUSED_MAP_F3_HEIGHT EQU 0
	; $F4
DEF UNUSED_MAP_F4 EQU $F4
DEF UNUSED_MAP_F4_WIDTH EQU 0
DEF UNUSED_MAP_F4_HEIGHT EQU 0
	; $F5
DEF LORELEIS_ROOM EQU $F5
DEF LORELEIS_ROOM_WIDTH EQU 5
DEF LORELEIS_ROOM_HEIGHT EQU 6
	; $F6
DEF BRUNOS_ROOM EQU $F6
DEF BRUNOS_ROOM_WIDTH EQU 5
DEF BRUNOS_ROOM_HEIGHT EQU 6
	; $F7
DEF AGATHAS_ROOM EQU $F7
DEF AGATHAS_ROOM_WIDTH EQU 5
DEF AGATHAS_ROOM_HEIGHT EQU 6
DEF INDOORGROUP_POKEMON_LEAGUE_3 EQU $F8
DEF NUM_MAPS EQU $F8

; Indoor maps, such as houses, use this as the Map ID in their exit warps
; This map ID takes the player back to the last outdoor map they were on, stored in wLastMap
DEF LAST_MAP EQU $ff

ASSERT NUM_MAPS <= LAST_MAP, "map IDs overlap LAST_MAP"
