DEF BAG_ITEM_CAPACITY EQU 20
DEF PC_ITEM_CAPACITY  EQU 50

; text box IDs
	; $01
DEF MESSAGE_BOX EQU 1
	; $02
	; $03 unused
DEF MENU_TEMPLATE_03 EQU 3
	; $04
DEF FIELD_MOVE_MON_MENU EQU 4
	; $05
DEF JP_MOCHIMONO_MENU_TEMPLATE EQU 5
	; $06
DEF USE_TOSS_MENU_TEMPLATE EQU 6
	; $07 unused
DEF MENU_TEMPLATE_07 EQU 7
	; $08
DEF JP_SAVE_MESSAGE_MENU_TEMPLATE EQU 8
	; $09
DEF JP_SPEED_OPTIONS_MENU_TEMPLATE EQU 9
	; $0a
	; $0b
DEF BATTLE_MENU_TEMPLATE EQU $B
	; $0c
DEF SWITCH_STATS_CANCEL_MENU_TEMPLATE EQU $C
	; $0d
DEF LIST_MENU_BOX EQU $D
	; $0e
DEF BUY_SELL_QUIT_MENU_TEMPLATE EQU $E
	; $0f
DEF MONEY_BOX_TEMPLATE EQU $F
	; $10 unused
DEF MENU_TEMPLATE_10 EQU $10
	; $11
DEF MON_SPRITE_POPUP EQU $11
	; $12
DEF JP_AH_MENU_TEMPLATE EQU $12
	; $13
DEF MONEY_BOX EQU $13
	; $14
DEF TWO_OPTION_MENU EQU $14
	; $15
DEF BUY_SELL_QUIT_MENU EQU $15
	; $16
	; $17
	; $18
	; $19
	; $1a
DEF JP_POKEDEX_MENU_TEMPLATE EQU $1A
	; $1b
DEF SAFARI_BATTLE_MENU_TEMPLATE EQU $1B

; two option menu constants
; TwoOptionMenuStrings indexes (see data/yes_no_menu_strings.asm)
	; 0
DEF YES_NO_MENU EQU 0
	; 1
DEF NORTH_WEST_MENU EQU 1
	; 2
DEF SOUTH_EAST_MENU EQU 2
	; 3
DEF WIDE_YES_NO_MENU EQU 3
	; 4
DEF NORTH_EAST_MENU EQU 4
	; 5
DEF TRADE_CANCEL_MENU EQU 5
	; 6
DEF HEAL_CANCEL_MENU EQU 6
	; 7
DEF NO_YES_MENU EQU 7
DEF NUM_TWO_OPTION_MENUS EQU 8

; wTwoOptionMenuID
DEF BIT_SECOND_MENU_OPTION_DEFAULT EQU 7

; menu exit method constants for list menus and the buy/sell/quit menu
DEF CHOSE_MENU_ITEM   EQU 1 ; pressed A
DEF CANCELLED_MENU    EQU 2 ; pressed B

; menu exit method constants for two-option menus
DEF CHOSE_FIRST_ITEM  EQU 1
DEF CHOSE_SECOND_ITEM EQU 2

; move mon constants
	; 0
DEF BOX_TO_PARTY EQU 0
	; 1
DEF PARTY_TO_BOX EQU 1
	; 2
DEF DAYCARE_TO_PARTY EQU 2
	; 3
DEF PARTY_TO_DAYCARE EQU 3

; party menu types
; PartyMenuMessagePointers indexes (see engine/menus/party_menu.asm)
	; $00
DEF NORMAL_PARTY_MENU EQU 0
	; $01
DEF USE_ITEM_PARTY_MENU EQU 1
	; $02
DEF BATTLE_PARTY_MENU EQU 2
	; $03
DEF TMHM_PARTY_MENU EQU 3
	; $04
DEF SWAP_MONS_PARTY_MENU EQU 4
	; $05
DEF EVO_STONE_PARTY_MENU EQU 5
; party menu message IDs
; PartyMenuItemUseMessagePointers indexes (see engine/menus/party_menu.asm)
DEF FIRST_PARTY_MENU_TEXT_ID EQU $F0
	; $F0
DEF ANTIDOTE_MSG EQU $F0
	; $F1
DEF BURN_HEAL_MSG EQU $F1
	; $F2
DEF ICE_HEAL_MSG EQU $F2
	; $F3
DEF AWAKENING_MSG EQU $F3
	; $F4
DEF PARALYZ_HEAL_MSG EQU $F4
	; $F5
DEF POTION_MSG EQU $F5
	; $F6
DEF FULL_HEAL_MSG EQU $F6
	; $F7
DEF REVIVE_MSG EQU $F7
	; $F8
DEF RARE_CANDY_MSG EQU $F8

; naming screen types
	; 0
DEF NAME_PLAYER_SCREEN EQU 0
	; 1
DEF NAME_RIVAL_SCREEN EQU 1
	; 2
DEF NAME_MON_SCREEN EQU 2

; Stats box layout (see engine/pokemon/status_screen.asm)
	; 0
DEF STATUS_SCREEN_STATS_BOX EQU 0
	; 1
DEF LEVEL_UP_STATS_BOX EQU 1
