; {stat}_(UP|DOWN)(1|2) means that the move raises the user's (or lowers the target's) corresponding stat modifier by 1 (or 2) stages
; {status condition}_SIDE_EFFECT means that the move has a side chance of causing that condition
; {status condition}_EFFECT means that the move causes the status condition every time it hits the target

; MoveEffectPointerTable indexes (see data/moves/effects_pointers.asm)
	; $00
DEF NO_ADDITIONAL_EFFECT EQU 0
	; $01 unused
DEF EFFECT_01 EQU 1
	; $02
DEF POISON_SIDE_EFFECT1 EQU 2
	; $03
DEF DRAIN_HP_EFFECT EQU 3
	; $04
DEF BURN_SIDE_EFFECT1 EQU 4
	; $05
DEF FREEZE_SIDE_EFFECT1 EQU 5
	; $06
DEF PARALYZE_SIDE_EFFECT1 EQU 6
	; $07 Explosion, Self Destruct
DEF EXPLODE_EFFECT EQU 7
	; $08
DEF DREAM_EATER_EFFECT EQU 8
	; $09
DEF MIRROR_MOVE_EFFECT EQU 9
	; $0A
DEF ATTACK_UP1_EFFECT EQU $A
	; $0B
DEF DEFENSE_UP1_EFFECT EQU $B
	; $0C
DEF SPEED_UP1_EFFECT EQU $C
	; $0D
DEF SPECIAL_UP1_EFFECT EQU $D
	; $0E
DEF ACCURACY_UP1_EFFECT EQU $E
	; $0F
DEF EVASION_UP1_EFFECT EQU $F
	; $10
DEF PAY_DAY_EFFECT EQU $10
	; $11
DEF SWIFT_EFFECT EQU $11
	; $12
DEF ATTACK_DOWN1_EFFECT EQU $12
	; $13
DEF DEFENSE_DOWN1_EFFECT EQU $13
	; $14
DEF SPEED_DOWN1_EFFECT EQU $14
	; $15
DEF SPECIAL_DOWN1_EFFECT EQU $15
	; $16
DEF ACCURACY_DOWN1_EFFECT EQU $16
	; $17
DEF EVASION_DOWN1_EFFECT EQU $17
	; $18
DEF CONVERSION_EFFECT EQU $18
	; $19
DEF HAZE_EFFECT EQU $19
	; $1A
DEF BIDE_EFFECT EQU $1A
	; $1B
DEF THRASH_PETAL_DANCE_EFFECT EQU $1B
	; $1C
DEF SWITCH_AND_TELEPORT_EFFECT EQU $1C
	; $1D
DEF TWO_TO_FIVE_ATTACKS_EFFECT EQU $1D
	; $1E unused
DEF EFFECT_1E EQU $1E
	; $1F
DEF FLINCH_SIDE_EFFECT1 EQU $1F
	; $20
DEF SLEEP_EFFECT EQU $20
	; $21
DEF POISON_SIDE_EFFECT2 EQU $21
	; $22
DEF BURN_SIDE_EFFECT2 EQU $22
	; $23 unused (Blizzard in JP Red/Green)
DEF FREEZE_SIDE_EFFECT2 EQU $23
	; $24
DEF PARALYZE_SIDE_EFFECT2 EQU $24
	; $25
DEF FLINCH_SIDE_EFFECT2 EQU $25
	; $26 moves like Horn Drill
DEF OHKO_EFFECT EQU $26
	; $27 moves like Solar Beam
DEF CHARGE_EFFECT EQU $27
	; $28
DEF SUPER_FANG_EFFECT EQU $28
	; $29 Seismic Toss, Night Shade, Sonic Boom, Dragon Rage, Psywave
DEF SPECIAL_DAMAGE_EFFECT EQU $29
	; $2A moves like Wrap
DEF TRAPPING_EFFECT EQU $2A
	; $2B
DEF FLY_EFFECT EQU $2B
	; $2C
DEF ATTACK_TWICE_EFFECT EQU $2C
	; $2D Jump Kick and Hi Jump Kick effect
DEF JUMP_KICK_EFFECT EQU $2D
	; $2E
DEF MIST_EFFECT EQU $2E
	; $2F
DEF FOCUS_ENERGY_EFFECT EQU $2F
	; $30 moves like Double Edge
DEF RECOIL_EFFECT EQU $30
	; $31 Confuse Ray, Supersonic (not the move Confusion)
DEF CONFUSION_EFFECT EQU $31
	; $32
DEF ATTACK_UP2_EFFECT EQU $32
	; $33
DEF DEFENSE_UP2_EFFECT EQU $33
	; $34
DEF SPEED_UP2_EFFECT EQU $34
	; $35
DEF SPECIAL_UP2_EFFECT EQU $35
	; $36
DEF ACCURACY_UP2_EFFECT EQU $36
	; $37
DEF EVASION_UP2_EFFECT EQU $37
	; $38 Recover, Softboiled, Rest
DEF HEAL_EFFECT EQU $38
	; $39
DEF TRANSFORM_EFFECT EQU $39
	; $3A
DEF ATTACK_DOWN2_EFFECT EQU $3A
	; $3B
DEF DEFENSE_DOWN2_EFFECT EQU $3B
	; $3C
DEF SPEED_DOWN2_EFFECT EQU $3C
	; $3D
DEF SPECIAL_DOWN2_EFFECT EQU $3D
	; $3E
DEF ACCURACY_DOWN2_EFFECT EQU $3E
	; $3F
DEF EVASION_DOWN2_EFFECT EQU $3F
	; $40
DEF LIGHT_SCREEN_EFFECT EQU $40
	; $41
DEF REFLECT_EFFECT EQU $41
	; $42
DEF POISON_EFFECT EQU $42
	; $43
DEF PARALYZE_EFFECT EQU $43
	; $44
DEF ATTACK_DOWN_SIDE_EFFECT EQU $44
	; $45
DEF DEFENSE_DOWN_SIDE_EFFECT EQU $45
	; $46
DEF SPEED_DOWN_SIDE_EFFECT EQU $46
	; $47
DEF SPECIAL_DOWN_SIDE_EFFECT EQU $47
	; $48
	; $49
	; $4A
	; $4B
	; $4C
DEF CONFUSION_SIDE_EFFECT EQU $4C
	; $4D
DEF TWINEEDLE_EFFECT EQU $4D
	; $4E
	; $4F
DEF SUBSTITUTE_EFFECT EQU $4F
	; $50
DEF HYPER_BEAM_EFFECT EQU $50
	; $51
DEF RAGE_EFFECT EQU $51
	; $52
DEF MIMIC_EFFECT EQU $52
	; $53
DEF METRONOME_EFFECT EQU $53
	; $54
DEF LEECH_SEED_EFFECT EQU $54
	; $55
DEF SPLASH_EFFECT EQU $55
	; $56
DEF DISABLE_EFFECT EQU $56
DEF NUM_MOVE_EFFECTS EQU $56
