; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - AttackAnimationPointers (see data/moves/animations.asm)
; - MoveSoundTable (see data/moves/sfx.asm)
	; 00
DEF NO_MOVE EQU 0
	; 01
DEF POUND EQU 1
	; 02
DEF KARATE_CHOP EQU 2
	; 03
DEF DOUBLESLAP EQU 3
	; 04
DEF COMET_PUNCH EQU 4
	; 05
DEF MEGA_PUNCH EQU 5
	; 06
DEF PAY_DAY EQU 6
	; 07
DEF FIRE_PUNCH EQU 7
	; 08
DEF ICE_PUNCH EQU 8
	; 09
DEF THUNDERPUNCH EQU 9
	; 0a
DEF SCRATCH EQU $A
	; 0b
DEF VICEGRIP EQU $B
	; 0c
DEF GUILLOTINE EQU $C
	; 0d
DEF RAZOR_WIND EQU $D
	; 0e
DEF SWORDS_DANCE EQU $E
	; 0f
DEF CUT EQU $F
	; 10
DEF GUST EQU $10
	; 11
DEF WING_ATTACK EQU $11
	; 12
DEF WHIRLWIND EQU $12
	; 13
DEF FLY EQU $13
	; 14
DEF BIND EQU $14
	; 15
DEF SLAM EQU $15
	; 16
DEF VINE_WHIP EQU $16
	; 17
DEF STOMP EQU $17
	; 18
DEF DOUBLE_KICK EQU $18
	; 19
DEF MEGA_KICK EQU $19
	; 1a
DEF JUMP_KICK EQU $1A
	; 1b
DEF ROLLING_KICK EQU $1B
	; 1c
DEF SAND_ATTACK EQU $1C
	; 1d
DEF HEADBUTT EQU $1D
	; 1e
DEF HORN_ATTACK EQU $1E
	; 1f
DEF FURY_ATTACK EQU $1F
	; 20
DEF HORN_DRILL EQU $20
	; 21
DEF TACKLE EQU $21
	; 22
DEF BODY_SLAM EQU $22
	; 23
DEF WRAP EQU $23
	; 24
DEF TAKE_DOWN EQU $24
	; 25
DEF THRASH EQU $25
	; 26
DEF DOUBLE_EDGE EQU $26
	; 27
DEF TAIL_WHIP EQU $27
	; 28
DEF POISON_STING EQU $28
	; 29
DEF TWINEEDLE EQU $29
	; 2a
DEF PIN_MISSILE EQU $2A
	; 2b
DEF LEER EQU $2B
	; 2c
DEF BITE EQU $2C
	; 2d
DEF GROWL EQU $2D
	; 2e
DEF ROAR EQU $2E
	; 2f
DEF SING EQU $2F
	; 30
DEF SUPERSONIC EQU $30
	; 31
DEF SONICBOOM EQU $31
	; 32
DEF DISABLE EQU $32
	; 33
DEF ACID EQU $33
	; 34
DEF EMBER EQU $34
	; 35
DEF FLAMETHROWER EQU $35
	; 36
DEF MIST EQU $36
	; 37
DEF WATER_GUN EQU $37
	; 38
DEF HYDRO_PUMP EQU $38
	; 39
DEF SURF EQU $39
	; 3a
DEF ICE_BEAM EQU $3A
	; 3b
DEF BLIZZARD EQU $3B
	; 3c
DEF PSYBEAM EQU $3C
	; 3d
DEF BUBBLEBEAM EQU $3D
	; 3e
DEF AURORA_BEAM EQU $3E
	; 3f
DEF HYPER_BEAM EQU $3F
	; 40
DEF PECK EQU $40
	; 41
DEF DRILL_PECK EQU $41
	; 42
DEF SUBMISSION EQU $42
	; 43
DEF LOW_KICK EQU $43
	; 44
DEF COUNTER EQU $44
	; 45
DEF SEISMIC_TOSS EQU $45
	; 46
DEF STRENGTH EQU $46
	; 47
DEF ABSORB EQU $47
	; 48
DEF MEGA_DRAIN EQU $48
	; 49
DEF LEECH_SEED EQU $49
	; 4a
DEF GROWTH EQU $4A
	; 4b
DEF RAZOR_LEAF EQU $4B
	; 4c
DEF SOLARBEAM EQU $4C
	; 4d
DEF POISONPOWDER EQU $4D
	; 4e
DEF STUN_SPORE EQU $4E
	; 4f
DEF SLEEP_POWDER EQU $4F
	; 50
DEF PETAL_DANCE EQU $50
	; 51
DEF STRING_SHOT EQU $51
	; 52
DEF DRAGON_RAGE EQU $52
	; 53
DEF FIRE_SPIN EQU $53
	; 54
DEF THUNDERSHOCK EQU $54
	; 55
DEF THUNDERBOLT EQU $55
	; 56
DEF THUNDER_WAVE EQU $56
	; 57
DEF THUNDER EQU $57
	; 58
DEF ROCK_THROW EQU $58
	; 59
DEF EARTHQUAKE EQU $59
	; 5a
DEF FISSURE EQU $5A
	; 5b
DEF DIG EQU $5B
	; 5c
DEF TOXIC EQU $5C
	; 5d
DEF CONFUSION EQU $5D
	; 5e
DEF PSYCHIC_M EQU $5E
	; 5f
DEF HYPNOSIS EQU $5F
	; 60
DEF MEDITATE EQU $60
	; 61
DEF AGILITY EQU $61
	; 62
DEF QUICK_ATTACK EQU $62
	; 63
DEF RAGE EQU $63
	; 64
DEF TELEPORT EQU $64
	; 65
DEF NIGHT_SHADE EQU $65
	; 66
DEF MIMIC EQU $66
	; 67
DEF SCREECH EQU $67
	; 68
DEF DOUBLE_TEAM EQU $68
	; 69
DEF RECOVER EQU $69
	; 6a
DEF HARDEN EQU $6A
	; 6b
DEF MINIMIZE EQU $6B
	; 6c
DEF SMOKESCREEN EQU $6C
	; 6d
DEF CONFUSE_RAY EQU $6D
	; 6e
DEF WITHDRAW EQU $6E
	; 6f
DEF DEFENSE_CURL EQU $6F
	; 70
DEF BARRIER EQU $70
	; 71
DEF LIGHT_SCREEN EQU $71
	; 72
DEF HAZE EQU $72
	; 73
DEF REFLECT EQU $73
	; 74
DEF FOCUS_ENERGY EQU $74
	; 75
DEF BIDE EQU $75
	; 76
DEF METRONOME EQU $76
	; 77
DEF MIRROR_MOVE EQU $77
	; 78
DEF SELFDESTRUCT EQU $78
	; 79
DEF EGG_BOMB EQU $79
	; 7a
DEF LICK EQU $7A
	; 7b
DEF SMOG EQU $7B
	; 7c
DEF SLUDGE EQU $7C
	; 7d
DEF BONE_CLUB EQU $7D
	; 7e
DEF FIRE_BLAST EQU $7E
	; 7f
DEF WATERFALL EQU $7F
	; 80
DEF CLAMP EQU $80
	; 81
DEF SWIFT EQU $81
	; 82
DEF SKULL_BASH EQU $82
	; 83
DEF SPIKE_CANNON EQU $83
	; 84
DEF CONSTRICT EQU $84
	; 85
DEF AMNESIA EQU $85
	; 86
DEF KINESIS EQU $86
	; 87
DEF SOFTBOILED EQU $87
	; 88
DEF HI_JUMP_KICK EQU $88
	; 89
DEF GLARE EQU $89
	; 8a
DEF DREAM_EATER EQU $8A
	; 8b
DEF POISON_GAS EQU $8B
	; 8c
DEF BARRAGE EQU $8C
	; 8d
DEF LEECH_LIFE EQU $8D
	; 8e
DEF LOVELY_KISS EQU $8E
	; 8f
DEF SKY_ATTACK EQU $8F
	; 90
DEF TRANSFORM EQU $90
	; 91
DEF BUBBLE EQU $91
	; 92
DEF DIZZY_PUNCH EQU $92
	; 93
DEF SPORE EQU $93
	; 94
DEF FLASH EQU $94
	; 95
DEF PSYWAVE EQU $95
	; 96
DEF SPLASH EQU $96
	; 97
DEF ACID_ARMOR EQU $97
	; 98
DEF CRABHAMMER EQU $98
	; 99
DEF EXPLOSION EQU $99
	; 9a
DEF FURY_SWIPES EQU $9A
	; 9b
DEF BONEMERANG EQU $9B
	; 9c
DEF REST EQU $9C
	; 9d
DEF ROCK_SLIDE EQU $9D
	; 9e
DEF HYPER_FANG EQU $9E
	; 9f
DEF SHARPEN EQU $9F
	; a0
DEF CONVERSION EQU $A0
	; a1
DEF TRI_ATTACK EQU $A1
	; a2
DEF SUPER_FANG EQU $A2
	; a3
DEF SLASH EQU $A3
	; a4
DEF SUBSTITUTE EQU $A4
	; a5
DEF STRUGGLE EQU $A5
DEF NUM_ATTACKS EQU $A5

DEF CANNOT_MOVE EQU $ff

	; Moves do double duty as animation identifiers.

DEF SHOWPIC_ANIM EQU $A6
DEF STATUS_AFFECTED_ANIM EQU $A7
DEF ANIM_A8 EQU $A8
DEF ENEMY_HUD_SHAKE_ANIM EQU $A9
DEF TRADE_BALL_DROP_ANIM EQU $AA
DEF TRADE_BALL_SHAKE_ANIM EQU $AB
DEF TRADE_BALL_TILT_ANIM EQU $AC
DEF TRADE_BALL_POOF_ANIM EQU $AD
	; use X Attack/Defense/Speed/Special
DEF XSTATITEM_ANIM EQU $AE
DEF XSTATITEM_DUPLICATE_ANIM EQU $AF
DEF SHRINKING_SQUARE_ANIM EQU $B0
DEF ANIM_B1 EQU $B1
DEF ANIM_B2 EQU $B2
DEF ANIM_B3 EQU $B3
DEF ANIM_B4 EQU $B4
DEF ANIM_B5 EQU $B5
DEF ANIM_B6 EQU $B6
DEF ANIM_B7 EQU $B7
DEF ANIM_B8 EQU $B8
DEF ANIM_B9 EQU $B9
	; Plays when a monster is burned or poisoned
DEF BURN_PSN_ANIM EQU $BA
DEF ANIM_BB EQU $BB
DEF SLP_PLAYER_ANIM EQU $BC
	; sleeping monster
DEF SLP_ANIM EQU $BD
DEF CONF_PLAYER_ANIM EQU $BE
	; confused monster
DEF CONF_ANIM EQU $BF
DEF SLIDE_DOWN_ANIM EQU $C0
	; toss Poké Ball
DEF TOSS_ANIM EQU $C1
	; shaking Poké Ball when catching monster
DEF SHAKE_ANIM EQU $C2
	; puff of smoke
DEF POOF_ANIM EQU $C3
	; trainer knocks away Poké Ball
DEF BLOCKBALL_ANIM EQU $C4
	; toss Great Ball
DEF GREATTOSS_ANIM EQU $C5
	; toss Ultra Ball or Master Ball
DEF ULTRATOSS_ANIM EQU $C6
DEF SHAKE_SCREEN_ANIM EQU $C7
	; monster disappears
DEF HIDEPIC_ANIM EQU $C8
	; throw rock
DEF ROCK_ANIM EQU $C9
	; throw bait
DEF BAIT_ANIM EQU $CA

DEF NUM_ATTACK_ANIMS EQU $CA
