; special effects that are part of move animations
; SpecialEffectPointers associates them with effect routines (see data/battle_anims/special_effect_pointers.asm)
DEF FIRST_SE_ID EQU $C0
	; $D8 used in Psywave/Night Shade/Psychic etc.
DEF SE_WAVY_SCREEN EQU $D8
	; $D9 used in Substitute (turns the pokemon into a mini sprite)
DEF SE_SUBSTITUTE_MON EQU $D9
	; $DA used in Double Team
DEF SE_SHAKE_BACK_AND_FORTH EQU $DA
	; $DB used in Whirlwind
DEF SE_SLIDE_ENEMY_MON_OFF EQU $DB
	; $DC used in Seismic Toss
DEF SE_SHOW_ENEMY_MON_PIC EQU $DC
	; $DD used in Low Kick/Quick Attack/Seismic Toss etc.
DEF SE_SHOW_MON_PIC EQU $DD
	; $DE used in Seismic Toss
DEF SE_BLINK_ENEMY_MON EQU $DE
	; $DF used in Seismic Toss
DEF SE_HIDE_ENEMY_MON_PIC EQU $DF
	; $E0 unused
DEF SE_FLASH_ENEMY_MON_PIC EQU $E0
	; $E1 used in lots of animations
DEF SE_DELAY_ANIMATION_10 EQU $E1
	; $E2 used in Growth/Focus Energy/Hyper Beam etc.
DEF SE_SPIRAL_BALLS_INWARD EQU $E2
	; $E3 unused
DEF SE_SHAKE_ENEMY_HUD_2 EQU $E3
	; $E4
DEF SE_SHAKE_ENEMY_HUD EQU $E4
	; $E5 used in Softboiled
DEF SE_SLIDE_MON_HALF_OFF EQU $E5
	; $E6 used in Petal Dance
DEF SE_PETALS_FALLING EQU $E6
	; $E7 used in Razor Leaf
DEF SE_LEAVES_FALLING EQU $E7
	; $E8 used in Transform
DEF SE_TRANSFORM_MON EQU $E8
	; $E9 used in Acid Armor
DEF SE_SLIDE_MON_DOWN_AND_HIDE EQU $E9
	; $EA used in Minimize
DEF SE_MINIMIZE_MON EQU $EA
	; $EB used in Splash
DEF SE_BOUNCE_UP_AND_DOWN EQU $EB
	; $EC used in an unused animation
DEF SE_SHOOT_MANY_BALLS_UPWARD EQU $EC
	; $ED used in Teleport/Sky Attack
DEF SE_SHOOT_BALLS_UPWARD EQU $ED
	; $EE used in Teleport/Sky Attack
DEF SE_SQUISH_MON_PIC EQU $EE
	; $EF
DEF SE_HIDE_MON_PIC EQU $EF
	; $F0 used in Mist/Double Edge/Absorb/etc.
DEF SE_LIGHT_SCREEN_PALETTE EQU $F0
	; $F1 used in Tackle/Body Slam/etc.
DEF SE_RESET_MON_POSITION EQU $F1
	; $F2 used in Tackle/Body Slam/etc.
DEF SE_MOVE_MON_HORIZONTALLY EQU $F2
	; $F3 used in Recover
DEF SE_BLINK_MON EQU $F3
	; $F4 used in Seismic Toss/Low Kick/etc.
DEF SE_SLIDE_MON_OFF EQU $F4
	; $F5
DEF SE_FLASH_MON_PIC EQU $F5
	; $F6 used in Withdraw/Waterfall/fainting
DEF SE_SLIDE_MON_DOWN EQU $F6
	; $F7 used in Dig/Waterfall/etc.
DEF SE_SLIDE_MON_UP EQU $F7
	; $F8 used in Confusion/Psychic/etc.
DEF SE_FLASH_SCREEN_LONG EQU $F8
	; $F9 used in Smokescreen/Smog/etc.
DEF SE_DARKEN_MON_PALETTE EQU $F9
	; $FA used in Mist/Surf/Toxic/etc.
DEF SE_WATER_DROPLETS_EVERYWHERE EQU $FA
	; $FB used in Earthquake/Fissure/etc.
DEF SE_SHAKE_SCREEN EQU $FB
	; $FC used in Leer/Thunderpunch/etc.
DEF SE_RESET_SCREEN_PALETTE EQU $FC
	; $FD used in Hyper Beam/Thunderpunch/etc.
DEF SE_DARK_SCREEN_PALETTE EQU $FD
	; $FE used in Cut/Take Down/etc.
DEF SE_DARK_SCREEN_FLASH EQU $FE

; subanimations that are part of move animations
; SubanimationPointers indexes (see data/battle_anims/subanimations.asm)

; The 0 or 1 in the name of a subanim indicates whether to use tileset 0 or 1 data/moves/animations.asm.
; "Both" indicates either can be used for different images using the same animation.
DEF SUBANIM_0_STAR EQU 0
DEF SUBANIM_0_STAR_TWICE EQU 1
DEF SUBANIM_0_STAR_THRICE EQU 2
DEF SUBANIM_0_STAR_DESCENDING EQU 3
DEF SUBANIM_1_STAR_BIG_MOVING EQU 4
DEF SUBANIM_1_STAR_BIG EQU 5
DEF SUBANIM_0_BALL_TOSS_HIGH EQU 6
DEF SUBANIM_0_BALL_TOSS_MIDDLE EQU 7
DEF SUBANIM_0_BALL_TOSS_LOW EQU 8
DEF SUBANIM_0_BALL_SHAKE_ENEMY EQU 9
DEF SUBANIM_0_BALL_POOF_ENEMY EQU $A
DEF SUBANIM_0_BALL_BLOCK EQU $B
DEF SUBANIM_1_FLAME_COLUMN_1 EQU $C
DEF SUBANIM_1_FLAME_COLUMN_2 EQU $D
DEF SUBANIM_1_FLAME_COLUMN_3 EQU $E
DEF SUBANIM_0_SCRATCHES EQU $F
DEF SUBANIM_1_TORNADO EQU $10
DEF SUBANIM_1_FLAMES EQU $11
DEF SUBANIM_0_HEART_1_MUSIC EQU $12
DEF SUBANIM_1_BLOB_TOSS EQU $13
DEF SUBANIM_1_BLOB_DRIP_ENEMY EQU $14
DEF SUBANIM_1_SHOUT EQU $15
DEF SUBANIM_0_SLICE EQU $16
DEF SUBANIM_0_BIRDIES_CIRCLING_ENEMY EQU $17
DEF SUBANIM_1_SWORDS_CIRCLING EQU $18
DEF SUBANIM_1_CLOUD_TOSS EQU $19
DEF SUBANIM_0_WATER_COLUMNS EQU $1A
DEF SUBANIM_1_SEED_TOSS EQU $1B
DEF SUBANIM_1_SEED_LAND EQU $1C
DEF SUBANIM_0_ROCKS_LIFT EQU $1D
DEF SUBANIM_0_ROCKS_TOSS EQU $1E
DEF SUBANIM_1_FLAME_BEAM EQU $1F
DEF SUBANIM_1_FLAME_STAR EQU $20
DEF SUBANIM_0_CIRCLES_1_SQUARES_CENTERING_ENEMY EQU $21
DEF SUBANIM_0_CIRCLE_1_SQUARE_TOSS_BACK EQU $22
DEF SUBANIM_0_BIND EQU $23
DEF SUBANIM_0_STATUS_PARALYZED EQU $24
DEF SUBANIM_0_STATUS_CONFUSED EQU $25
DEF SUBANIM_0_STATUS_CONFUSED_ENEMY EQU $26
DEF SUBANIM_0_STATUS_POISONED EQU $27
DEF SUBANIM_1_SAND EQU $28
DEF SUBANIM_1_LIGHTNING_BALL EQU $29
DEF SUBANIM_0_SLICE_BOTH_SIDES EQU $2A
DEF SUBANIM_1_LIGHTNING EQU $2B
DEF SUBANIM_0_WATER_DROPLETS EQU $2C
DEF SUBANIM_0_CIRCLES_CENTERING EQU $2D
DEF SUBANIM_0_BEAM EQU $2E
DEF SUBANIM_0_ICE_RISE EQU $2F
DEF SUBANIM_0_ROCKS_FALL_ENEMY EQU $30
DEF SUBANIM_0_SOUND_WAVE EQU $31
	; unused
DEF SUBANIM_0_CIRCLE_1_SQUARE_HALF_TOSS EQU $32
DEF SUBANIM_1_BARRIER EQU $33
DEF SUBANIM_1_SELFDESTRUCT EQU $34
DEF SUBANIM_0_WATER_BUBBLES EQU $35
DEF SUBANIM_0_CIRCLES_FALLING EQU $36
DEF SUBANIM_0_STRING_SHOT EQU $37
DEF SUBANIM_0_ICE_FALL EQU $38
	; unused
DEF SUBANIM_0_CIRCLE_1_SQUARE_APPEARS EQU $39
DEF SUBANIM_0_STATUS_SLEEP EQU $3A
DEF SUBANIM_0_STATUS_SLEEP_ENEMY EQU $3B
	; unused
DEF SUBANIM_0_WATER_1_FIRE_BARRIER EQU $3C
	; unused
DEF SUBANIM_0_WATER_1_FIRE_GEYSER EQU $3D
DEF SUBANIM_1_STAR_BIG_TOSS EQU $3E
DEF SUBANIM_1_STARS_SMALL_TOSS EQU $3F
DEF SUBANIM_1_MUSIC_CIRCLING_ENEMY EQU $40
DEF SUBANIM_1_CIRCLE_BLACK_TOSS EQU $41
DEF SUBANIM_1_EXPLOSION_SMALL_ENEMY EQU $42
DEF SUBANIM_0_CIRCLE_1_SQUARE_CLOSING EQU $43
DEF SUBANIM_1_LEAVES_TOSS EQU $44
DEF SUBANIM_0_HORN_JAB_TWICE EQU $45
DEF SUBANIM_0_HORN_JAB_THRICE EQU $46
DEF SUBANIM_0_BALL_POOF EQU $47
DEF SUBANIM_2_TRADE_BALL_DROP EQU $48
DEF SUBANIM_2_TRADE_BALL_SHAKE EQU $49
DEF SUBANIM_2_TRADE_BALL_APPEAR EQU $4A
DEF SUBANIM_2_TRADE_BALL_POOF EQU $4B
DEF SUBANIM_0_EGG_SHAKING EQU $4C
DEF SUBANIM_1_TRIANGLE_TOSS EQU $4D
DEF SUBANIM_1_SPHERE_BIG EQU $4E
DEF SUBANIM_1_SPHERE_BIG_RISE EQU $4F
DEF SUBANIM_1_SPHERE_BIG_FALL EQU $50
DEF SUBANIM_0_SHELL EQU $51
DEF SUBANIM_0_COIN_BOUNCE EQU $52
DEF SUBANIM_0_SAFARI_ROCK EQU $53
DEF SUBANIM_0_SAFARI_BAIT EQU $54
DEF SUBANIM_0_STAR_HIGH EQU $55
DEF NUM_SUBANIMS EQU $56

; types of subanimations
DEF SUBANIMTYPE_NORMAL EQU 0
DEF SUBANIMTYPE_HVFLIP EQU 1
DEF SUBANIMTYPE_HFLIP EQU 2
DEF SUBANIMTYPE_COORDFLIP EQU 3
DEF SUBANIMTYPE_REVERSE EQU 4
DEF SUBANIMTYPE_ENEMY EQU 5

; frame blocks that are part of subanimations
; FrameBlockPointers indexes (see data/battle_anims/frame_blocks.asm)
DEF FRAMEBLOCK_00 EQU 0
DEF FRAMEBLOCK_01 EQU 1
DEF FRAMEBLOCK_02 EQU 2
DEF FRAMEBLOCK_03 EQU 3
DEF FRAMEBLOCK_04 EQU 4
DEF FRAMEBLOCK_05 EQU 5
DEF FRAMEBLOCK_06 EQU 6
DEF FRAMEBLOCK_07 EQU 7
DEF FRAMEBLOCK_08 EQU 8
DEF FRAMEBLOCK_09 EQU 9
DEF FRAMEBLOCK_0A EQU $A
DEF FRAMEBLOCK_0B EQU $B
DEF FRAMEBLOCK_0C EQU $C
DEF FRAMEBLOCK_0D EQU $D
DEF FRAMEBLOCK_0E EQU $E
DEF FRAMEBLOCK_0F EQU $F
DEF FRAMEBLOCK_10 EQU $10
DEF FRAMEBLOCK_11 EQU $11
DEF FRAMEBLOCK_12 EQU $12
DEF FRAMEBLOCK_13 EQU $13
DEF FRAMEBLOCK_14 EQU $14
DEF FRAMEBLOCK_15 EQU $15
DEF FRAMEBLOCK_16 EQU $16
DEF FRAMEBLOCK_17 EQU $17
DEF FRAMEBLOCK_18 EQU $18
DEF FRAMEBLOCK_19 EQU $19
DEF FRAMEBLOCK_1A EQU $1A
DEF FRAMEBLOCK_1B EQU $1B
DEF FRAMEBLOCK_1C EQU $1C
DEF FRAMEBLOCK_1D EQU $1D
DEF FRAMEBLOCK_1E EQU $1E
DEF FRAMEBLOCK_1F EQU $1F
DEF FRAMEBLOCK_20 EQU $20
DEF FRAMEBLOCK_21 EQU $21
DEF FRAMEBLOCK_22 EQU $22
DEF FRAMEBLOCK_23 EQU $23
DEF FRAMEBLOCK_24 EQU $24
DEF FRAMEBLOCK_25 EQU $25
DEF FRAMEBLOCK_26 EQU $26
DEF FRAMEBLOCK_27 EQU $27
DEF FRAMEBLOCK_28 EQU $28
DEF FRAMEBLOCK_29 EQU $29
DEF FRAMEBLOCK_2A EQU $2A
DEF FRAMEBLOCK_2B EQU $2B
DEF FRAMEBLOCK_2C EQU $2C
DEF FRAMEBLOCK_2D EQU $2D
DEF FRAMEBLOCK_2E EQU $2E
DEF FRAMEBLOCK_2F EQU $2F
DEF FRAMEBLOCK_30 EQU $30
DEF FRAMEBLOCK_31 EQU $31
DEF FRAMEBLOCK_32 EQU $32
DEF FRAMEBLOCK_33 EQU $33
DEF FRAMEBLOCK_34 EQU $34
DEF FRAMEBLOCK_35 EQU $35
DEF FRAMEBLOCK_36 EQU $36
DEF FRAMEBLOCK_37 EQU $37
DEF FRAMEBLOCK_38 EQU $38
DEF FRAMEBLOCK_39 EQU $39
DEF FRAMEBLOCK_3A EQU $3A
DEF FRAMEBLOCK_3B EQU $3B
DEF FRAMEBLOCK_3C EQU $3C
DEF FRAMEBLOCK_3D EQU $3D
DEF FRAMEBLOCK_3E EQU $3E
DEF FRAMEBLOCK_3F EQU $3F
DEF FRAMEBLOCK_40 EQU $40
DEF FRAMEBLOCK_41 EQU $41
DEF FRAMEBLOCK_42 EQU $42
DEF FRAMEBLOCK_43 EQU $43
DEF FRAMEBLOCK_44 EQU $44
DEF FRAMEBLOCK_45 EQU $45
DEF FRAMEBLOCK_46 EQU $46
DEF FRAMEBLOCK_47 EQU $47
DEF FRAMEBLOCK_SMALL_BLACK_CIRCLE EQU $48
DEF FRAMEBLOCK_LARGE_BLACK_CIRCLE EQU $49
DEF FRAMEBLOCK_4A EQU $4A
DEF FRAMEBLOCK_4B EQU $4B
DEF FRAMEBLOCK_4C EQU $4C
DEF FRAMEBLOCK_4D EQU $4D
DEF FRAMEBLOCK_4E EQU $4E
DEF FRAMEBLOCK_4F EQU $4F
DEF FRAMEBLOCK_50 EQU $50
DEF FRAMEBLOCK_51 EQU $51
DEF FRAMEBLOCK_52 EQU $52
DEF FRAMEBLOCK_53 EQU $53
DEF FRAMEBLOCK_54 EQU $54
DEF FRAMEBLOCK_55 EQU $55
DEF FRAMEBLOCK_56 EQU $56
DEF FRAMEBLOCK_57 EQU $57
DEF FRAMEBLOCK_58 EQU $58
DEF FRAMEBLOCK_59 EQU $59
DEF FRAMEBLOCK_5A EQU $5A
DEF FRAMEBLOCK_5B EQU $5B
DEF FRAMEBLOCK_5C EQU $5C
DEF FRAMEBLOCK_5D EQU $5D
DEF FRAMEBLOCK_5E EQU $5E
DEF FRAMEBLOCK_5F EQU $5F
DEF FRAMEBLOCK_60 EQU $60
DEF FRAMEBLOCK_61 EQU $61
DEF FRAMEBLOCK_62 EQU $62
DEF FRAMEBLOCK_63 EQU $63
DEF FRAMEBLOCK_64 EQU $64
DEF FRAMEBLOCK_65 EQU $65
DEF FRAMEBLOCK_66 EQU $66
DEF FRAMEBLOCK_67 EQU $67
DEF FRAMEBLOCK_68 EQU $68
DEF FRAMEBLOCK_69 EQU $69
DEF FRAMEBLOCK_6A EQU $6A
DEF FRAMEBLOCK_6B EQU $6B
DEF FRAMEBLOCK_6C EQU $6C
DEF FRAMEBLOCK_6D EQU $6D
DEF FRAMEBLOCK_6E EQU $6E
DEF FRAMEBLOCK_6F EQU $6F
DEF FRAMEBLOCK_70 EQU $70
DEF FRAMEBLOCK_71 EQU $71
DEF FRAMEBLOCK_72 EQU $72
DEF FRAMEBLOCK_73 EQU $73
DEF FRAMEBLOCK_74 EQU $74
DEF FRAMEBLOCK_75 EQU $75
DEF FRAMEBLOCK_76 EQU $76
DEF FRAMEBLOCK_77 EQU $77
DEF FRAMEBLOCK_78 EQU $78
DEF FRAMEBLOCK_79 EQU $79
DEF NUM_FRAMEBLOCKS EQU $7A

; base coordinates that are part of subanimations
; FrameBlockBaseCoords indexes (see data/battle_anims/base_coords.asm)
DEF BASECOORD_00 EQU 0
DEF BASECOORD_01 EQU 1
DEF BASECOORD_02 EQU 2
DEF BASECOORD_03 EQU 3
DEF BASECOORD_04 EQU 4
DEF BASECOORD_05 EQU 5
DEF BASECOORD_06 EQU 6
DEF BASECOORD_07 EQU 7
DEF BASECOORD_08 EQU 8
DEF BASECOORD_09 EQU 9
DEF BASECOORD_0A EQU $A
DEF BASECOORD_0B EQU $B
DEF BASECOORD_0C EQU $C
DEF BASECOORD_0D EQU $D
DEF BASECOORD_0E EQU $E
DEF BASECOORD_0F EQU $F
DEF BASECOORD_10 EQU $10
DEF BASECOORD_11 EQU $11
DEF BASECOORD_12 EQU $12
DEF BASECOORD_13 EQU $13
DEF BASECOORD_14 EQU $14
DEF BASECOORD_15 EQU $15
DEF BASECOORD_16 EQU $16
DEF BASECOORD_17 EQU $17
DEF BASECOORD_18 EQU $18
DEF BASECOORD_19 EQU $19
DEF BASECOORD_1A EQU $1A
DEF BASECOORD_1B EQU $1B
DEF BASECOORD_1C EQU $1C
DEF BASECOORD_1D EQU $1D
DEF BASECOORD_1E EQU $1E
DEF BASECOORD_1F EQU $1F
DEF BASECOORD_20 EQU $20
DEF BASECOORD_21 EQU $21
DEF BASECOORD_22 EQU $22
DEF BASECOORD_23 EQU $23
DEF BASECOORD_24 EQU $24
DEF BASECOORD_25 EQU $25
DEF BASECOORD_26 EQU $26
DEF BASECOORD_27 EQU $27
DEF BASECOORD_28 EQU $28
DEF BASECOORD_29 EQU $29
DEF BASECOORD_2A EQU $2A
DEF BASECOORD_2B EQU $2B
DEF BASECOORD_2C EQU $2C
DEF BASECOORD_2D EQU $2D
DEF BASECOORD_2E EQU $2E
DEF BASECOORD_2F EQU $2F
DEF BASECOORD_30 EQU $30
DEF BASECOORD_31 EQU $31
DEF BASECOORD_32 EQU $32
DEF BASECOORD_33 EQU $33
DEF BASECOORD_34 EQU $34
DEF BASECOORD_35 EQU $35
DEF BASECOORD_36 EQU $36
DEF BASECOORD_37 EQU $37
DEF BASECOORD_38 EQU $38
DEF BASECOORD_39 EQU $39
DEF BASECOORD_3A EQU $3A
DEF BASECOORD_3B EQU $3B
DEF BASECOORD_3C EQU $3C
DEF BASECOORD_3D EQU $3D
DEF BASECOORD_3E EQU $3E
DEF BASECOORD_3F EQU $3F
DEF BASECOORD_40 EQU $40
DEF BASECOORD_41 EQU $41
DEF BASECOORD_42 EQU $42
DEF BASECOORD_43 EQU $43
DEF BASECOORD_44 EQU $44
DEF BASECOORD_45 EQU $45
DEF BASECOORD_46 EQU $46
DEF BASECOORD_47 EQU $47
DEF BASECOORD_48 EQU $48
DEF BASECOORD_49 EQU $49
DEF BASECOORD_4A EQU $4A
DEF BASECOORD_4B EQU $4B
DEF BASECOORD_4C EQU $4C
DEF BASECOORD_4D EQU $4D
DEF BASECOORD_4E EQU $4E
DEF BASECOORD_4F EQU $4F
DEF BASECOORD_50 EQU $50
DEF BASECOORD_51 EQU $51
DEF BASECOORD_52 EQU $52
DEF BASECOORD_53 EQU $53
DEF BASECOORD_54 EQU $54
DEF BASECOORD_55 EQU $55
DEF BASECOORD_56 EQU $56
DEF BASECOORD_57 EQU $57
DEF BASECOORD_58 EQU $58
DEF BASECOORD_59 EQU $59
DEF BASECOORD_5A EQU $5A
DEF BASECOORD_5B EQU $5B
DEF BASECOORD_5C EQU $5C
DEF BASECOORD_5D EQU $5D
DEF BASECOORD_5E EQU $5E
DEF BASECOORD_5F EQU $5F
DEF BASECOORD_60 EQU $60
DEF BASECOORD_61 EQU $61
DEF BASECOORD_62 EQU $62
DEF BASECOORD_63 EQU $63
DEF BASECOORD_64 EQU $64
DEF BASECOORD_65 EQU $65
DEF BASECOORD_66 EQU $66
DEF BASECOORD_67 EQU $67
DEF BASECOORD_68 EQU $68
DEF BASECOORD_69 EQU $69
DEF BASECOORD_6A EQU $6A
DEF BASECOORD_6B EQU $6B
DEF BASECOORD_6C EQU $6C
DEF BASECOORD_6D EQU $6D
DEF BASECOORD_6E EQU $6E
DEF BASECOORD_6F EQU $6F
DEF BASECOORD_70 EQU $70
DEF BASECOORD_71 EQU $71
DEF BASECOORD_72 EQU $72
DEF BASECOORD_73 EQU $73
DEF BASECOORD_74 EQU $74
DEF BASECOORD_75 EQU $75
DEF BASECOORD_76 EQU $76
DEF BASECOORD_77 EQU $77
DEF BASECOORD_78 EQU $78
DEF BASECOORD_79 EQU $79
DEF BASECOORD_7A EQU $7A
DEF BASECOORD_7B EQU $7B
DEF BASECOORD_7C EQU $7C
DEF BASECOORD_7D EQU $7D
DEF BASECOORD_7E EQU $7E
DEF BASECOORD_7F EQU $7F
DEF BASECOORD_80 EQU $80
DEF BASECOORD_81 EQU $81
DEF BASECOORD_82 EQU $82
DEF BASECOORD_83 EQU $83
DEF BASECOORD_84 EQU $84
DEF BASECOORD_85 EQU $85
DEF BASECOORD_86 EQU $86
DEF BASECOORD_87 EQU $87
DEF BASECOORD_88 EQU $88
DEF BASECOORD_89 EQU $89
DEF BASECOORD_8A EQU $8A
DEF BASECOORD_8B EQU $8B
DEF BASECOORD_8C EQU $8C
DEF BASECOORD_8D EQU $8D
DEF BASECOORD_8E EQU $8E
DEF BASECOORD_8F EQU $8F
DEF BASECOORD_90 EQU $90
DEF BASECOORD_91 EQU $91
DEF BASECOORD_92 EQU $92
DEF BASECOORD_93 EQU $93
DEF BASECOORD_94 EQU $94
DEF BASECOORD_95 EQU $95
DEF BASECOORD_96 EQU $96
DEF BASECOORD_97 EQU $97
DEF BASECOORD_98 EQU $98
DEF BASECOORD_99 EQU $99
DEF BASECOORD_9A EQU $9A
DEF BASECOORD_9B EQU $9B
DEF BASECOORD_9C EQU $9C
DEF BASECOORD_9D EQU $9D
DEF BASECOORD_9E EQU $9E
DEF BASECOORD_9F EQU $9F
DEF BASECOORD_A0 EQU $A0
DEF BASECOORD_A1 EQU $A1
DEF BASECOORD_A2 EQU $A2
DEF BASECOORD_A3 EQU $A3
DEF BASECOORD_A4 EQU $A4
DEF BASECOORD_A5 EQU $A5
DEF BASECOORD_A6 EQU $A6
DEF BASECOORD_A7 EQU $A7
DEF BASECOORD_A8 EQU $A8
DEF BASECOORD_A9 EQU $A9
DEF BASECOORD_AA EQU $AA
DEF BASECOORD_AB EQU $AB
DEF BASECOORD_AC EQU $AC
DEF BASECOORD_AD EQU $AD
DEF BASECOORD_AE EQU $AE
DEF BASECOORD_AF EQU $AF
DEF BASECOORD_B0 EQU $B0
DEF NUM_BASECOORDS EQU $B1

; frame block modes that are part of subanimations
DEF FRAMEBLOCKMODE_00 EQU 0
DEF FRAMEBLOCKMODE_01 EQU 1
DEF FRAMEBLOCKMODE_02 EQU 2
DEF FRAMEBLOCKMODE_03 EQU 3
DEF FRAMEBLOCKMODE_04 EQU 4
