; pal/blk packets
; SetPalFunctions indexes (see engine/gfx/palettes.asm)
	; $00
DEF SET_PAL_BATTLE_BLACK EQU 0
	; $01
DEF SET_PAL_BATTLE EQU 1
	; $02
DEF SET_PAL_TOWN_MAP EQU 2
	; $03
DEF SET_PAL_STATUS_SCREEN EQU 3
	; $04
DEF SET_PAL_POKEDEX EQU 4
	; $05
DEF SET_PAL_SLOTS EQU 5
	; $06
DEF SET_PAL_TITLE_SCREEN EQU 6
	; $07
DEF SET_PAL_NIDORINO_INTRO EQU 7
	; $08
DEF SET_PAL_GENERIC EQU 8
	; $09
DEF SET_PAL_OVERWORLD EQU 9
	; $0A
DEF SET_PAL_PARTY_MENU EQU $A
	; $0B
DEF SET_PAL_POKEMON_WHOLE_SCREEN EQU $B
	; $0C
DEF SET_PAL_GAME_FREAK_INTRO EQU $C
	; $0D
DEF SET_PAL_TRAINER_CARD EQU $D

DEF SET_PAL_PARTY_MENU_HP_BARS EQU $fc
DEF SET_PAL_DEFAULT EQU $ff

; sgb palettes
; SuperPalettes indexes (see data/sgb/sgb_palettes.asm)
	; $00
DEF PAL_ROUTE EQU 0
	; $01
DEF PAL_PALLET EQU 1
	; $02
DEF PAL_VIRIDIAN EQU 2
	; $03
DEF PAL_PEWTER EQU 3
	; $04
DEF PAL_CERULEAN EQU 4
	; $05
DEF PAL_LAVENDER EQU 5
	; $06
DEF PAL_VERMILION EQU 6
	; $07
DEF PAL_CELADON EQU 7
	; $08
DEF PAL_FUCHSIA EQU 8
	; $09
DEF PAL_CINNABAR EQU 9
	; $0A
DEF PAL_INDIGO EQU $A
	; $0B
DEF PAL_SAFFRON EQU $B
	; $0C
DEF PAL_TOWNMAP EQU $C
	; $0D
DEF PAL_LOGO1 EQU $D
	; $0E
DEF PAL_LOGO2 EQU $E
	; $0F
DEF PAL_0F EQU $F
	; $10
DEF PAL_MEWMON EQU $10
	; $11
DEF PAL_BLUEMON EQU $11
	; $12
DEF PAL_REDMON EQU $12
	; $13
DEF PAL_CYANMON EQU $13
	; $14
DEF PAL_PURPLEMON EQU $14
	; $15
DEF PAL_BROWNMON EQU $15
	; $16
DEF PAL_GREENMON EQU $16
	; $17
DEF PAL_PINKMON EQU $17
	; $18
DEF PAL_YELLOWMON EQU $18
	; $19
DEF PAL_GRAYMON EQU $19
	; $1A
DEF PAL_SLOTS1 EQU $1A
	; $1B
DEF PAL_SLOTS2 EQU $1B
	; $1C
DEF PAL_SLOTS3 EQU $1C
	; $1D
DEF PAL_SLOTS4 EQU $1D
	; $1E
DEF PAL_BLACK EQU $1E
	; $1F
DEF PAL_GREENBAR EQU $1F
	; $20
DEF PAL_YELLOWBAR EQU $20
	; $21
DEF PAL_REDBAR EQU $21
	; $22
DEF PAL_BADGE EQU $22
	; $23
DEF PAL_CAVE EQU $23
	; $24
DEF PAL_GAMEFREAK EQU $24
DEF NUM_SGB_PALS EQU $25
