; base data struct members (see data/pokemon/base_stats/*.asm)
DEF BASE_DEX_NO EQU 0
DEF BASE_STATS EQU 1
DEF BASE_HP EQU 1
DEF BASE_ATK EQU 2
DEF BASE_DEF EQU 3
DEF BASE_SPD EQU 4
DEF BASE_SPC EQU 5
DEF BASE_TYPES EQU 6
DEF BASE_TYPE_1 EQU 6
DEF BASE_TYPE_2 EQU 7
DEF BASE_CATCH_RATE EQU 8
DEF BASE_EXP EQU 9
DEF BASE_PIC_SIZE EQU $A
DEF BASE_FRONTPIC EQU $B
DEF BASE_BACKPIC EQU $D
DEF BASE_MOVES EQU $F
DEF BASE_GROWTH_RATE EQU $13
DEF BASE_TMHM EQU $14
DEF BASE_DATA_SIZE EQU $1C

; party_struct members (see macros/ram.asm)
DEF MON_SPECIES EQU 0
DEF MON_HP EQU 1
DEF MON_BOX_LEVEL EQU 3
DEF MON_STATUS EQU 4
DEF MON_TYPE EQU 5
DEF MON_TYPE1 EQU 5
DEF MON_TYPE2 EQU 6
DEF MON_CATCH_RATE EQU 7
DEF MON_MOVES EQU 8
DEF MON_OTID EQU $C
DEF MON_EXP EQU $E
DEF MON_HP_EXP EQU $11
DEF MON_ATK_EXP EQU $13
DEF MON_DEF_EXP EQU $15
DEF MON_SPD_EXP EQU $17
DEF MON_SPC_EXP EQU $19
DEF MON_DVS EQU $1B
DEF MON_PP EQU $1D
DEF BOXMON_STRUCT_LENGTH EQU $21 ; $21
DEF MON_LEVEL EQU $21
DEF MON_STATS EQU $22
DEF MON_MAXHP EQU $22
DEF MON_ATK EQU $24
DEF MON_DEF EQU $26
DEF MON_SPD EQU $28
DEF MON_SPC EQU $2A
DEF PARTYMON_STRUCT_LENGTH EQU $2C ; $2c

DEF PARTY_LENGTH EQU 6

DEF MONS_PER_BOX EQU 20
DEF NUM_BOXES    EQU 12

DEF HOF_MON           EQU $10
DEF HOF_TEAM          EQU PARTY_LENGTH * HOF_MON
DEF HOF_TEAM_CAPACITY EQU 50

; mon data locations
; Note that some values are not supported by all functions that use these values.
	; 0
DEF PLAYER_PARTY_DATA EQU 0
	; 1
DEF ENEMY_PARTY_DATA EQU 1
	; 2
DEF BOX_DATA EQU 2
	; 3
DEF DAYCARE_DATA EQU 3
	; 4
DEF BATTLE_MON_DATA EQU 4

; Evolution types
	; 1
DEF EVOLVE_LEVEL EQU 1
	; 2
DEF EVOLVE_ITEM EQU 2
	; 3
DEF EVOLVE_TRADE EQU 3

; evolution data (see data/pokemon/evos_moves.asm)
DEF NUM_EVOS_IN_BUFFER EQU 3

; wMonHGrowthRate values
; GrowthRateTable indexes (see data/growth_rates.asm)
DEF GROWTH_MEDIUM_FAST EQU 0
DEF GROWTH_SLIGHTLY_FAST EQU 1
DEF GROWTH_SLIGHTLY_SLOW EQU 2
DEF GROWTH_MEDIUM_SLOW EQU 3
DEF GROWTH_FAST EQU 4
DEF GROWTH_SLOW EQU 5
DEF NUM_GROWTH_RATES EQU 6

; wild data (see data/wild/maps/*.asm)
DEF NUM_WILDMONS EQU 10
DEF WILDDATA_LENGTH EQU 1 + NUM_WILDMONS * 2

; PP in box_struct (see macros/ram.asm)
DEF PP_UP_MASK EQU %11000000 ; number of PP Up used
DEF PP_MASK    EQU %00111111 ; currently remaining PP
