; wSlotMachineFlags
	; 6
DEF BIT_SLOTS_CAN_WIN EQU 6
	; 7
DEF BIT_SLOTS_CAN_WIN_WITH_7_OR_BAR EQU 7

; wMiscFlags
	; 0
DEF BIT_SEEN_BY_TRAINER EQU 0
	; 1
DEF BIT_BOULDER_DUST EQU 1
	; 2
DEF BIT_TURNING EQU 2
	; 3
DEF BIT_USING_GENERIC_PC EQU 3
	; 4
DEF BIT_NO_SPRITE_UPDATES EQU 4
	; 5
DEF BIT_NO_MENU_BUTTON_SOUND EQU 5
	; 6
DEF BIT_TRIED_PUSH_BOULDER EQU 6
	; 7
DEF BIT_PUSHED_BOULDER EQU 7

; wAutoTextBoxDrawingControl
DEF BIT_NO_AUTO_TEXT_BOX EQU 0

; wTextPredefFlag
DEF BIT_TEXT_PREDEF EQU 0

; wFontLoaded
DEF BIT_FONT_LOADED EQU 0

; wCurrentMapScriptFlags
	; 5
DEF BIT_CUR_MAP_LOADED_1 EQU 5
	; 6
DEF BIT_CUR_MAP_LOADED_2 EQU 6
	; 7
DEF BIT_CUR_MAP_USED_ELEVATOR EQU 7

; wOptions
DEF TEXT_DELAY_MASK EQU %111
	; 6
DEF BIT_BATTLE_SHIFT EQU 6
	; 7
DEF BIT_BATTLE_ANIMATION EQU 7

DEF TEXT_DELAY_FAST   EQU %001 ; 1
DEF TEXT_DELAY_MEDIUM EQU %011 ; 3
DEF TEXT_DELAY_SLOW   EQU %101 ; 5

; wLetterPrintingDelayFlags
	; 0
DEF BIT_FAST_TEXT_DELAY EQU 0
	; 1
DEF BIT_TEXT_DELAY EQU 1

; wCurMapTileset
DEF BIT_NO_PREVIOUS_MAP EQU 7

; wCurrentBoxNum
DEF BIT_HAS_CHANGED_BOXES EQU 7
DEF BOX_NUM_MASK EQU %01111111

; wObtainedBadges, wBeatGymFlags
	; 0
DEF BIT_BOULDERBADGE EQU 0
	; 1
DEF BIT_CASCADEBADGE EQU 1
	; 2
DEF BIT_THUNDERBADGE EQU 2
	; 3
DEF BIT_RAINBOWBADGE EQU 3
	; 4
DEF BIT_SOULBADGE EQU 4
	; 5
DEF BIT_MARSHBADGE EQU 5
	; 6
DEF BIT_VOLCANOBADGE EQU 6
	; 7
DEF BIT_EARTHBADGE EQU 7
DEF NUM_BADGES EQU 8

; wStatusFlags1
	; 0
DEF BIT_STRENGTH_ACTIVE EQU 0
	; 1
DEF BIT_SURF_ALLOWED EQU 1
	; 2 ; unused
	; 3
DEF BIT_GOT_OLD_ROD EQU 3
	; 4
DEF BIT_GOT_GOOD_ROD EQU 4
	; 5
DEF BIT_GOT_SUPER_ROD EQU 5
	; 6
DEF BIT_GAVE_SAFFRON_GUARDS_DRINK EQU 6
	; 7
DEF BIT_UNUSED_CARD_KEY EQU 7

; wStatusFlags2
	; 0
DEF BIT_WILD_ENCOUNTER_COOLDOWN EQU 0
	; 1
DEF BIT_NO_AUDIO_FADE_OUT EQU 1

; wStatusFlags3
	; 0
DEF BIT_INIT_TRADE_CENTER_FACING EQU 0
	; 1-2 ; unused
	; 3
DEF BIT_WARP_FROM_CUR_SCRIPT EQU 3
	; 4
DEF BIT_ON_DUNGEON_WARP EQU 4
	; 5
DEF BIT_NO_NPC_FACE_PLAYER EQU 5
	; 6
DEF BIT_TALKED_TO_TRAINER EQU 6
	; 7
DEF BIT_PRINT_END_BATTLE_TEXT EQU 7

; wStatusFlags4
	; 0
DEF BIT_GOT_LAPRAS EQU 0
	; 1
DEF BIT_UNKNOWN_4_1 EQU 1
	; 2
DEF BIT_USED_POKECENTER EQU 2
	; 3
DEF BIT_GOT_STARTER EQU 3
	; 4
DEF BIT_NO_BATTLES EQU 4
	; 5
DEF BIT_BATTLE_OVER_OR_BLACKOUT EQU 5
	; 6
DEF BIT_LINK_CONNECTED EQU 6
	; 7
DEF BIT_INIT_SCRIPTED_MOVEMENT EQU 7

; wStatusFlags5
	; 0
DEF BIT_SCRIPTED_NPC_MOVEMENT EQU 0
	; 1
DEF BIT_UNKNOWN_5_1 EQU 1
	; 2
DEF BIT_UNKNOWN_5_2 EQU 2
	; 3 ; unused
	; 4
DEF BIT_UNKNOWN_5_4 EQU 4
	; 5
DEF BIT_DISABLE_JOYPAD EQU 5
	; 6
DEF BIT_NO_TEXT_DELAY EQU 6
	; 7
DEF BIT_SCRIPTED_MOVEMENT_STATE EQU 7

; wStatusFlags6
	; 0
DEF BIT_GAME_TIMER_COUNTING EQU 0
	; 1
DEF BIT_DEBUG_MODE EQU 1
	; 2
DEF BIT_FLY_OR_DUNGEON_WARP EQU 2
	; 3
DEF BIT_FLY_WARP EQU 3
	; 4
DEF BIT_DUNGEON_WARP EQU 4
	; 5
DEF BIT_ALWAYS_ON_BIKE EQU 5
	; 6
DEF BIT_ESCAPE_WARP EQU 6

; wStatusFlags7
	; 0
DEF BIT_TEST_BATTLE EQU 0
	; 1
DEF BIT_NO_MAP_MUSIC EQU 1
	; 2
DEF BIT_FORCED_WARP EQU 2
	; 3
DEF BIT_TRAINER_BATTLE EQU 3
	; 4
DEF BIT_USE_CUR_MAP_SCRIPT EQU 4
	; 5-6 ; unused
	; 7
DEF BIT_USED_FLY EQU 7

; wElite4Flags
	; 0
DEF BIT_UNUSED_BEAT_ELITE_4 EQU 0
	; 1
DEF BIT_STARTED_ELITE_4 EQU 1

; wMovementFlags
	; 0
DEF BIT_STANDING_ON_DOOR EQU 0
	; 1
DEF BIT_EXITING_DOOR EQU 1
	; 2
DEF BIT_STANDING_ON_WARP EQU 2
	; 3-5 ; unused
	; 6
DEF BIT_LEDGE_OR_FISHING EQU 6
	; 7
DEF BIT_SPINNING EQU 7

; hFindPathFlags
	; 0
DEF BIT_PATH_FOUND_Y EQU 0
	; 1
DEF BIT_PATH_FOUND_X EQU 1

; hNPCPlayerRelativePosFlags
	; 0
DEF BIT_PLAYER_LOWER_Y EQU 0
	; 1
DEF BIT_PLAYER_LOWER_X EQU 1

; rLCDC
DEF LCDC_DEFAULT EQU LCDC_ON | LCDC_WIN_9C00 | LCDC_WIN_ON | LCDC_BLOCK21 | LCDC_BG_9800 | LCDC_OBJ_8 | LCDC_OBJ_ON | LCDC_BG_ON
