; EmotionBubblesPointerTable indexes (see engine/overworld/emotion_bubbles.asm)
	; 0
DEF EXCLAMATION_BUBBLE EQU 0
	; 1
DEF QUESTION_BUBBLE EQU 1
	; 2
DEF SMILE_BUBBLE EQU 2

; slot symbols
DEF SLOTS7      EQU $0200
DEF SLOTSBAR    EQU $0604
DEF SLOTSCHERRY EQU $0A08
DEF SLOTSFISH   EQU $0E0C
DEF SLOTSBIRD   EQU $1210
DEF SLOTSMOUSE  EQU $1614

; StartSlotMachine dialogs
DEF SLOTS_OUTOFORDER   EQU $fd
DEF SLOTS_OUTTOLUNCH   EQU $fe
DEF SLOTS_SOMEONESKEYS EQU $ff

; in game trades
; TradeMons indexes (see data/events/trades.asm)
DEF TRADE_FOR_TERRY EQU 0
DEF TRADE_FOR_MARCEL EQU 1
	; unused
DEF TRADE_FOR_CHIKUCHIKU EQU 2
DEF TRADE_FOR_SAILOR EQU 3
DEF TRADE_FOR_DUX EQU 4
DEF TRADE_FOR_MARC EQU 5
DEF TRADE_FOR_LOLA EQU 6
DEF TRADE_FOR_DORIS EQU 7
DEF TRADE_FOR_CRINKLES EQU 8
DEF TRADE_FOR_SPOT EQU 9
DEF NUM_NPC_TRADES EQU $A

; in game trade dialog sets
; InGameTradeTextPointers indexes (see engine/events/in_game_trades.asm)
DEF TRADE_DIALOGSET_CASUAL EQU 0
DEF TRADE_DIALOGSET_EVOLUTION EQU 1
DEF TRADE_DIALOGSET_HAPPY EQU 2
DEF NUM_TRADE_DIALOGSETS EQU 3

; OaksAideScript results
DEF OAKS_AIDE_BAG_FULL        EQU $00
DEF OAKS_AIDE_GOT_ITEM        EQU $01
DEF OAKS_AIDE_NOT_ENOUGH_MONS EQU $80
DEF OAKS_AIDE_REFUSED         EQU $ff
