; overworld sprites
; SpriteSheetPointerTable indexes (see data/sprites/sprites.asm)
	; $00
DEF SPRITE_NONE EQU 0
	; $01
DEF SPRITE_RED EQU 1
	; $02
DEF SPRITE_BLUE EQU 2
	; $03
DEF SPRITE_OAK EQU 3
	; $04
DEF SPRITE_YOUNGSTER EQU 4
	; $05
DEF SPRITE_MONSTER EQU 5
	; $06
DEF SPRITE_COOLTRAINER_F EQU 6
	; $07
DEF SPRITE_COOLTRAINER_M EQU 7
	; $08
DEF SPRITE_LITTLE_GIRL EQU 8
	; $09
DEF SPRITE_BIRD EQU 9
	; $0a
DEF SPRITE_MIDDLE_AGED_MAN EQU $A
	; $0b
DEF SPRITE_GAMBLER EQU $B
	; $0c
DEF SPRITE_SUPER_NERD EQU $C
	; $0d
DEF SPRITE_GIRL EQU $D
	; $0e
DEF SPRITE_HIKER EQU $E
	; $0f
DEF SPRITE_BEAUTY EQU $F
	; $10
DEF SPRITE_GENTLEMAN EQU $10
	; $11
DEF SPRITE_DAISY EQU $11
	; $12
DEF SPRITE_BIKER EQU $12
	; $13
DEF SPRITE_SAILOR EQU $13
	; $14
DEF SPRITE_COOK EQU $14
	; $15
DEF SPRITE_BIKE_SHOP_CLERK EQU $15
	; $16
DEF SPRITE_MR_FUJI EQU $16
	; $17
DEF SPRITE_GIOVANNI EQU $17
	; $18
DEF SPRITE_ROCKET EQU $18
	; $19
DEF SPRITE_CHANNELER EQU $19
	; $1a
DEF SPRITE_WAITER EQU $1A
	; $1b
DEF SPRITE_SILPH_WORKER_F EQU $1B
	; $1c
DEF SPRITE_MIDDLE_AGED_WOMAN EQU $1C
	; $1d
DEF SPRITE_BRUNETTE_GIRL EQU $1D
	; $1e
DEF SPRITE_LANCE EQU $1E
	; $1f
DEF SPRITE_UNUSED_SCIENTIST EQU $1F
	; $20
DEF SPRITE_SCIENTIST EQU $20
	; $21
DEF SPRITE_ROCKER EQU $21
	; $22
DEF SPRITE_SWIMMER EQU $22
	; $23
DEF SPRITE_SAFARI_ZONE_WORKER EQU $23
	; $24
DEF SPRITE_GYM_GUIDE EQU $24
	; $25
DEF SPRITE_GRAMPS EQU $25
	; $26
DEF SPRITE_CLERK EQU $26
	; $27
DEF SPRITE_FISHING_GURU EQU $27
	; $28
DEF SPRITE_GRANNY EQU $28
	; $29
DEF SPRITE_NURSE EQU $29
	; $2a
DEF SPRITE_LINK_RECEPTIONIST EQU $2A
	; $2b
DEF SPRITE_SILPH_PRESIDENT EQU $2B
	; $2c
DEF SPRITE_SILPH_WORKER_M EQU $2C
	; $2d
DEF SPRITE_WARDEN EQU $2D
	; $2e
DEF SPRITE_CAPTAIN EQU $2E
	; $2f
DEF SPRITE_FISHER EQU $2F
	; $30
DEF SPRITE_KOGA EQU $30
	; $31
DEF SPRITE_GUARD EQU $31
	; $32
DEF SPRITE_UNUSED_GUARD EQU $32
	; $33
DEF SPRITE_MOM EQU $33
	; $34
DEF SPRITE_BALDING_GUY EQU $34
	; $35
DEF SPRITE_LITTLE_BOY EQU $35
	; $36
DEF SPRITE_UNUSED_GAMEBOY_KID EQU $36
	; $37
DEF SPRITE_GAMEBOY_KID EQU $37
	; $38
DEF SPRITE_FAIRY EQU $38
	; $39
DEF SPRITE_AGATHA EQU $39
	; $3a
DEF SPRITE_BRUNO EQU $3A
	; $3b
DEF SPRITE_LORELEI EQU $3B
	; $3c
DEF SPRITE_SEEL EQU $3C
DEF FIRST_STILL_SPRITE EQU $3D
	; $3d
DEF SPRITE_POKE_BALL EQU $3D
	; $3e
DEF SPRITE_FOSSIL EQU $3E
	; $3f
DEF SPRITE_BOULDER EQU $3F
	; $40
DEF SPRITE_PAPER EQU $40
	; $41
DEF SPRITE_POKEDEX EQU $41
	; $42
DEF SPRITE_CLIPBOARD EQU $42
	; $43
DEF SPRITE_SNORLAX EQU $43
	; $44
DEF SPRITE_UNUSED_OLD_AMBER EQU $44
	; $45
DEF SPRITE_OLD_AMBER EQU $45
	; $46
DEF SPRITE_UNUSED_GAMBLER_ASLEEP_1 EQU $46
	; $47
DEF SPRITE_UNUSED_GAMBLER_ASLEEP_2 EQU $47
	; $48
DEF SPRITE_GAMBLER_ASLEEP EQU $48
DEF NUM_SPRITES EQU $48
