; sprite facing directions
	; $00
DEF SPRITE_FACING_DOWN EQU 0
	; $04
DEF SPRITE_FACING_UP EQU 4
	; $08
DEF SPRITE_FACING_LEFT EQU 8
	; $0C
DEF SPRITE_FACING_RIGHT EQU $C

	; $00
DEF NPC_MOVEMENT_DOWN EQU 0
	; $40
DEF NPC_MOVEMENT_UP EQU $40
	; $80
DEF NPC_MOVEMENT_LEFT EQU $80
	; $C0
DEF NPC_MOVEMENT_RIGHT EQU $C0

DEF NPC_CHANGE_FACING EQU $E0

; player direction constants
	; 0
DEF PLAYER_DIR_BIT_RIGHT EQU 0
	; 1
DEF PLAYER_DIR_BIT_LEFT EQU 1
	; 2
DEF PLAYER_DIR_BIT_DOWN EQU 2
	; 3
DEF PLAYER_DIR_BIT_UP EQU 3

DEF PLAYER_DIR_RIGHT EQU 1 << PLAYER_DIR_BIT_RIGHT
DEF PLAYER_DIR_LEFT  EQU 1 << PLAYER_DIR_BIT_LEFT
DEF PLAYER_DIR_DOWN  EQU 1 << PLAYER_DIR_BIT_DOWN
DEF PLAYER_DIR_UP    EQU 1 << PLAYER_DIR_BIT_UP
