DEF PLAYER_NAME_LENGTH  EQU 8
DEF STAT_NAME_LENGTH    EQU 10
DEF NAME_LENGTH         EQU 11
DEF ITEM_NAME_LENGTH    EQU 13
DEF TRAINER_NAME_LENGTH EQU 13
DEF MOVE_NAME_LENGTH    EQU 14
DEF GYM_CITY_LENGTH     EQU 17
DEF NAME_BUFFER_LENGTH  EQU 20

; PrintNumber, PrintBCDNumber
	; 5
DEF BIT_MONEY_SIGN EQU 5
	; 6
DEF BIT_LEFT_ALIGN EQU 6
	; 7
DEF BIT_LEADING_ZEROES EQU 7

DEF MONEY_SIGN     EQU 1 << BIT_MONEY_SIGN
DEF LEFT_ALIGN     EQU 1 << BIT_LEFT_ALIGN
DEF LEADING_ZEROES EQU 1 << BIT_LEADING_ZEROES

; special text IDs (see home/text_script.asm)
	; $d0
DEF TEXT_MON_FAINTED EQU $D0
	; $d1
DEF TEXT_BLACKED_OUT EQU $D1
	; $d2
DEF TEXT_REPEL_WORE_OFF EQU $D2
	; $d3
DEF TEXT_SAFARI_GAME_OVER EQU $D3

DEF TEXT_START_MENU EQU $00
