DEF OFF EQU $11
DEF ON  EQU $15


; ToggleableObjectStates indexes (see data/maps/toggleable_objects.asm)
; This lists the object_events that can be toggled by ShowObject/HideObject.
; The constants marked with an X are never used, because those object_events
; are not toggled on/off in any map's script.
; (The X-ed ones are either items or static Pokemon encounters that deactivate
; after battle and are detected in wToggleableObjectList.)


DEF TOGGLEMAP$0_ID EQU 0
	DEF TOGGLEMAP$0_NAME EQUS "PALLET_TOWN"
	; 00
DEF TOGGLE_PALLET_TOWN_OAK EQU 0

DEF TOGGLEMAP$1_ID EQU 1
	DEF TOGGLEMAP$1_NAME EQUS "VIRIDIAN_CITY"
	; 01
DEF TOGGLE_LYING_OLD_MAN EQU 1
	; 02
DEF TOGGLE_OLD_MAN EQU 2

DEF TOGGLEMAP$2_ID EQU 3
	DEF TOGGLEMAP$2_NAME EQUS "PEWTER_CITY"
	; 03
DEF TOGGLE_MUSEUM_GUY EQU 3
	; 04
DEF TOGGLE_GYM_GUY EQU 4

DEF TOGGLEMAP$3_ID EQU 5
	DEF TOGGLEMAP$3_NAME EQUS "CERULEAN_CITY"
	; 05
DEF TOGGLE_CERULEAN_RIVAL EQU 5
	; 06
DEF TOGGLE_CERULEAN_ROCKET EQU 6
	; 07
DEF TOGGLE_CERULEAN_GUARD_1 EQU 7
	; 08
DEF TOGGLE_CERULEAN_CAVE_GUY EQU 8
	; 09
DEF TOGGLE_CERULEAN_GUARD_2 EQU 9

DEF TOGGLEMAP$A_ID EQU $A
	DEF TOGGLEMAP$A_NAME EQUS "SAFFRON_CITY"
	; 0A
DEF TOGGLE_SAFFRON_CITY_1 EQU $A
	; 0B
DEF TOGGLE_SAFFRON_CITY_2 EQU $B
	; 0C
DEF TOGGLE_SAFFRON_CITY_3 EQU $C
	; 0D
DEF TOGGLE_SAFFRON_CITY_4 EQU $D
	; 0E
DEF TOGGLE_SAFFRON_CITY_5 EQU $E
	; 0F
DEF TOGGLE_SAFFRON_CITY_6 EQU $F
	; 10
DEF TOGGLE_SAFFRON_CITY_7 EQU $10
	; 11
DEF TOGGLE_SAFFRON_CITY_8 EQU $11
	; 12
DEF TOGGLE_SAFFRON_CITY_9 EQU $12
	; 13
DEF TOGGLE_SAFFRON_CITY_A EQU $13
	; 14
DEF TOGGLE_SAFFRON_CITY_B EQU $14
	; 15
DEF TOGGLE_SAFFRON_CITY_C EQU $15
	; 16
DEF TOGGLE_SAFFRON_CITY_D EQU $16
	; 17
DEF TOGGLE_SAFFRON_CITY_E EQU $17
	; 18
DEF TOGGLE_SAFFRON_CITY_F EQU $18

DEF TOGGLEMAP$D_ID EQU $19
	DEF TOGGLEMAP$D_NAME EQUS "ROUTE_2"
	; 19 X
DEF TOGGLE_ROUTE_2_ITEM_1 EQU $19
	; 1A X
DEF TOGGLE_ROUTE_2_ITEM_2 EQU $1A

DEF TOGGLEMAP$F_ID EQU $1B
	DEF TOGGLEMAP$F_NAME EQUS "ROUTE_4"
	; 1B X
DEF TOGGLE_ROUTE_4_ITEM EQU $1B

DEF TOGGLEMAP$14_ID EQU $1C
	DEF TOGGLEMAP$14_NAME EQUS "ROUTE_9"
	; 1C X
DEF TOGGLE_ROUTE_9_ITEM EQU $1C

DEF TOGGLEMAP$17_ID EQU $1D
	DEF TOGGLEMAP$17_NAME EQUS "ROUTE_12"
	; 1D
DEF TOGGLE_ROUTE_12_SNORLAX EQU $1D
	; 1E X
DEF TOGGLE_ROUTE_12_ITEM_1 EQU $1E
	; 1F X
DEF TOGGLE_ROUTE_12_ITEM_2 EQU $1F

DEF TOGGLEMAP$1A_ID EQU $20
	DEF TOGGLEMAP$1A_NAME EQUS "ROUTE_15"
	; 20 X
DEF TOGGLE_ROUTE_15_ITEM EQU $20

DEF TOGGLEMAP$1B_ID EQU $21
	DEF TOGGLEMAP$1B_NAME EQUS "ROUTE_16"
	; 21
DEF TOGGLE_ROUTE_16_SNORLAX EQU $21

DEF TOGGLEMAP$21_ID EQU $22
	DEF TOGGLEMAP$21_NAME EQUS "ROUTE_22"
	; 22
DEF TOGGLE_ROUTE_22_RIVAL_1 EQU $22
	; 23
DEF TOGGLE_ROUTE_22_RIVAL_2 EQU $23

DEF TOGGLEMAP$23_ID EQU $24
	DEF TOGGLEMAP$23_NAME EQUS "ROUTE_24"
	; 24
DEF TOGGLE_NUGGET_BRIDGE_GUY EQU $24
	; 25 X
DEF TOGGLE_ROUTE_24_ITEM EQU $25

DEF TOGGLEMAP$24_ID EQU $26
	DEF TOGGLEMAP$24_NAME EQUS "ROUTE_25"
	; 26 X
DEF TOGGLE_ROUTE_25_ITEM EQU $26

DEF TOGGLEMAP$27_ID EQU $27
	DEF TOGGLEMAP$27_NAME EQUS "BLUES_HOUSE"
	; 27
DEF TOGGLE_DAISY_SITTING EQU $27
	; 28
DEF TOGGLE_DAISY_WALKING EQU $28
	; 29
DEF TOGGLE_TOWN_MAP EQU $29

DEF TOGGLEMAP$28_ID EQU $2A
	DEF TOGGLEMAP$28_NAME EQUS "OAKS_LAB"
	; 2A
DEF TOGGLE_OAKS_LAB_RIVAL EQU $2A
	; 2B
DEF TOGGLE_STARTER_BALL_1 EQU $2B
	; 2C
DEF TOGGLE_STARTER_BALL_2 EQU $2C
	; 2D
DEF TOGGLE_STARTER_BALL_3 EQU $2D
	; 2E
DEF TOGGLE_OAKS_LAB_OAK_1 EQU $2E
	; 2F
DEF TOGGLE_POKEDEX_1 EQU $2F
	; 30
DEF TOGGLE_POKEDEX_2 EQU $30
	; 31
DEF TOGGLE_OAKS_LAB_OAK_2 EQU $31

DEF TOGGLEMAP$2D_ID EQU $32
	DEF TOGGLEMAP$2D_NAME EQUS "VIRIDIAN_GYM"
	; 32
DEF TOGGLE_VIRIDIAN_GYM_GIOVANNI EQU $32
	; 33 X
DEF TOGGLE_VIRIDIAN_GYM_ITEM EQU $33

DEF TOGGLEMAP$34_ID EQU $34
	DEF TOGGLEMAP$34_NAME EQUS "MUSEUM_1F"
	; 34
DEF TOGGLE_OLD_AMBER EQU $34

DEF TOGGLEMAP$E4_ID EQU $35
	DEF TOGGLEMAP$E4_NAME EQUS "CERULEAN_CAVE_1F"
	; 35 X
DEF TOGGLE_CERULEAN_CAVE_1F_ITEM_1 EQU $35
	; 36 X
DEF TOGGLE_CERULEAN_CAVE_1F_ITEM_2 EQU $36
	; 37 X
DEF TOGGLE_CERULEAN_CAVE_1F_ITEM_3 EQU $37

DEF TOGGLEMAP$8F_ID EQU $38
	DEF TOGGLEMAP$8F_NAME EQUS "POKEMON_TOWER_2F"
	; 38
DEF TOGGLE_POKEMON_TOWER_2F_RIVAL EQU $38

DEF TOGGLEMAP$90_ID EQU $39
	DEF TOGGLEMAP$90_NAME EQUS "POKEMON_TOWER_3F"
	; 39 X
DEF TOGGLE_POKEMON_TOWER_3F_ITEM EQU $39

DEF TOGGLEMAP$91_ID EQU $3A
	DEF TOGGLEMAP$91_NAME EQUS "POKEMON_TOWER_4F"
	; 3A X
DEF TOGGLE_POKEMON_TOWER_4F_ITEM_1 EQU $3A
	; 3B X
DEF TOGGLE_POKEMON_TOWER_4F_ITEM_2 EQU $3B
	; 3C X
DEF TOGGLE_POKEMON_TOWER_4F_ITEM_3 EQU $3C

DEF TOGGLEMAP$92_ID EQU $3D
	DEF TOGGLEMAP$92_NAME EQUS "POKEMON_TOWER_5F"
	; 3D X
DEF TOGGLE_POKEMON_TOWER_5F_ITEM EQU $3D

DEF TOGGLEMAP$93_ID EQU $3E
	DEF TOGGLEMAP$93_NAME EQUS "POKEMON_TOWER_6F"
	; 3E X
DEF TOGGLE_POKEMON_TOWER_6F_ITEM_1 EQU $3E
	; 3F X
DEF TOGGLE_POKEMON_TOWER_6F_ITEM_2 EQU $3F

DEF TOGGLEMAP$94_ID EQU $40
	DEF TOGGLEMAP$94_NAME EQUS "POKEMON_TOWER_7F"
	; 40 X
DEF TOGGLE_POKEMON_TOWER_7F_ROCKET_1 EQU $40
	; 41 X
DEF TOGGLE_POKEMON_TOWER_7F_ROCKET_2 EQU $41
	; 42 X
DEF TOGGLE_POKEMON_TOWER_7F_ROCKET_3 EQU $42
	; 43
DEF TOGGLE_POKEMON_TOWER_7F_MR_FUJI EQU $43

DEF TOGGLEMAP$95_ID EQU $44
	DEF TOGGLEMAP$95_NAME EQUS "MR_FUJIS_HOUSE"
	; 44
DEF TOGGLE_MR_FUJIS_HOUSE_MR_FUJI EQU $44

DEF TOGGLEMAP$84_ID EQU $45
	DEF TOGGLEMAP$84_NAME EQUS "CELADON_MANSION_ROOF_HOUSE"
	; 45
DEF TOGGLE_CELADON_MANSION_EEVEE_GIFT EQU $45

DEF TOGGLEMAP$87_ID EQU $46
	DEF TOGGLEMAP$87_NAME EQUS "GAME_CORNER"
	; 46
DEF TOGGLE_GAME_CORNER_ROCKET EQU $46

DEF TOGGLEMAP$9B_ID EQU $47
	DEF TOGGLEMAP$9B_NAME EQUS "WARDENS_HOUSE"
	; 47 X
DEF TOGGLE_WARDENS_HOUSE_ITEM EQU $47

DEF TOGGLEMAP$A5_ID EQU $48
	DEF TOGGLEMAP$A5_NAME EQUS "POKEMON_MANSION_1F"
	; 48 X
DEF TOGGLE_POKEMON_MANSION_1F_ITEM_1 EQU $48
	; 49 X
DEF TOGGLE_POKEMON_MANSION_1F_ITEM_2 EQU $49

DEF TOGGLEMAP$B1_ID EQU $4A
	DEF TOGGLEMAP$B1_NAME EQUS "FIGHTING_DOJO"
	; 4A
DEF TOGGLE_FIGHTING_DOJO_GIFT_1 EQU $4A
	; 4B
DEF TOGGLE_FIGHTING_DOJO_GIFT_2 EQU $4B

DEF TOGGLEMAP$B5_ID EQU $4C
	DEF TOGGLEMAP$B5_NAME EQUS "SILPH_CO_1F"
	; 4C
DEF TOGGLE_SILPH_CO_1F_RECEPTIONIST EQU $4C

DEF TOGGLEMAP$53_ID EQU $4D
	DEF TOGGLEMAP$53_NAME EQUS "POWER_PLANT"
	; 4D X
DEF TOGGLE_VOLTORB_1 EQU $4D
	; 4E X
DEF TOGGLE_VOLTORB_2 EQU $4E
	; 4F X
DEF TOGGLE_VOLTORB_3 EQU $4F
	; 50 X
DEF TOGGLE_ELECTRODE_1 EQU $50
	; 51 X
DEF TOGGLE_VOLTORB_4 EQU $51
	; 52 X
DEF TOGGLE_VOLTORB_5 EQU $52
	; 53 X
DEF TOGGLE_ELECTRODE_2 EQU $53
	; 54 X
DEF TOGGLE_VOLTORB_6 EQU $54
	; 55 X
DEF TOGGLE_ZAPDOS EQU $55
	; 56 X
DEF TOGGLE_POWER_PLANT_ITEM_1 EQU $56
	; 57 X
DEF TOGGLE_POWER_PLANT_ITEM_2 EQU $57
	; 58 X
DEF TOGGLE_POWER_PLANT_ITEM_3 EQU $58
	; 59 X
DEF TOGGLE_POWER_PLANT_ITEM_4 EQU $59
	; 5A X
DEF TOGGLE_POWER_PLANT_ITEM_5 EQU $5A

DEF TOGGLEMAP$C2_ID EQU $5B
	DEF TOGGLEMAP$C2_NAME EQUS "VICTORY_ROAD_2F"
	; 5B X
DEF TOGGLE_MOLTRES EQU $5B
	; 5C X
DEF TOGGLE_VICTORY_ROAD_2F_ITEM_1 EQU $5C
	; 5D X
DEF TOGGLE_VICTORY_ROAD_2F_ITEM_2 EQU $5D
	; 5E X
DEF TOGGLE_VICTORY_ROAD_2F_ITEM_3 EQU $5E
	; 5F X
DEF TOGGLE_VICTORY_ROAD_2F_ITEM_4 EQU $5F
	; 60
DEF TOGGLE_VICTORY_ROAD_2F_BOULDER EQU $60

DEF TOGGLEMAP$58_ID EQU $61
	DEF TOGGLEMAP$58_NAME EQUS "BILLS_HOUSE"
	; 61
DEF TOGGLE_BILL_POKEMON EQU $61
	; 62
DEF TOGGLE_BILL_1 EQU $62
	; 63
DEF TOGGLE_BILL_2 EQU $63

DEF TOGGLEMAP$33_ID EQU $64
	DEF TOGGLEMAP$33_NAME EQUS "VIRIDIAN_FOREST"
	; 64 X
DEF TOGGLE_VIRIDIAN_FOREST_ITEM_1 EQU $64
	; 65 X
DEF TOGGLE_VIRIDIAN_FOREST_ITEM_2 EQU $65
	; 66 X
DEF TOGGLE_VIRIDIAN_FOREST_ITEM_3 EQU $66

DEF TOGGLEMAP$3B_ID EQU $67
	DEF TOGGLEMAP$3B_NAME EQUS "MT_MOON_1F"
	; 67 X
DEF TOGGLE_MT_MOON_1F_ITEM_1 EQU $67
	; 68 X
DEF TOGGLE_MT_MOON_1F_ITEM_2 EQU $68
	; 69 X
DEF TOGGLE_MT_MOON_1F_ITEM_3 EQU $69
	; 6A X
DEF TOGGLE_MT_MOON_1F_ITEM_4 EQU $6A
	; 6B X
DEF TOGGLE_MT_MOON_1F_ITEM_5 EQU $6B
	; 6C X
DEF TOGGLE_MT_MOON_1F_ITEM_6 EQU $6C

DEF TOGGLEMAP$3D_ID EQU $6D
	DEF TOGGLEMAP$3D_NAME EQUS "MT_MOON_B2F"
	; 6D
DEF TOGGLE_MT_MOON_B2F_FOSSIL_1 EQU $6D
	; 6E
DEF TOGGLE_MT_MOON_B2F_FOSSIL_2 EQU $6E
	; 6F X
DEF TOGGLE_MT_MOON_B2F_ITEM_1 EQU $6F
	; 70 X
DEF TOGGLE_MT_MOON_B2F_ITEM_2 EQU $70

DEF TOGGLEMAP$60_ID EQU $71
	DEF TOGGLEMAP$60_NAME EQUS "SS_ANNE_2F"
	; 71
DEF TOGGLE_SS_ANNE_2F_RIVAL EQU $71

DEF TOGGLEMAP$66_ID EQU $72
	DEF TOGGLEMAP$66_NAME EQUS "SS_ANNE_1F_ROOMS"
	; 72 X
DEF TOGGLE_SS_ANNE_1F_ROOMS_ITEM EQU $72

DEF TOGGLEMAP$67_ID EQU $73
	DEF TOGGLEMAP$67_NAME EQUS "SS_ANNE_2F_ROOMS"
	; 73 X
DEF TOGGLE_SS_ANNE_2F_ROOMS_ITEM_1 EQU $73
	; 74 X
DEF TOGGLE_SS_ANNE_2F_ROOMS_ITEM_2 EQU $74

DEF TOGGLEMAP$68_ID EQU $75
	DEF TOGGLEMAP$68_NAME EQUS "SS_ANNE_B1F_ROOMS"
	; 75 X
DEF TOGGLE_SS_ANNE_B1F_ROOMS_ITEM_1 EQU $75
	; 76 X
DEF TOGGLE_SS_ANNE_B1F_ROOMS_ITEM_2 EQU $76
	; 77 X
DEF TOGGLE_SS_ANNE_B1F_ROOMS_ITEM_3 EQU $77

DEF TOGGLEMAP$C6_ID EQU $78
	DEF TOGGLEMAP$C6_NAME EQUS "VICTORY_ROAD_3F"
	; 78 X
DEF TOGGLE_VICTORY_ROAD_3F_ITEM_1 EQU $78
	; 79 X
DEF TOGGLE_VICTORY_ROAD_3F_ITEM_2 EQU $79
	; 7A
DEF TOGGLE_VICTORY_ROAD_3F_BOULDER EQU $7A

DEF TOGGLEMAP$C7_ID EQU $7B
	DEF TOGGLEMAP$C7_NAME EQUS "ROCKET_HIDEOUT_B1F"
	; 7B X
DEF TOGGLE_ROCKET_HIDEOUT_B1F_ITEM_1 EQU $7B
	; 7C X
DEF TOGGLE_ROCKET_HIDEOUT_B1F_ITEM_2 EQU $7C

DEF TOGGLEMAP$C8_ID EQU $7D
	DEF TOGGLEMAP$C8_NAME EQUS "ROCKET_HIDEOUT_B2F"
	; 7D X
DEF TOGGLE_ROCKET_HIDEOUT_B2F_ITEM_1 EQU $7D
	; 7E X
DEF TOGGLE_ROCKET_HIDEOUT_B2F_ITEM_2 EQU $7E
	; 7F X
DEF TOGGLE_ROCKET_HIDEOUT_B2F_ITEM_3 EQU $7F
	; 80 X
DEF TOGGLE_ROCKET_HIDEOUT_B2F_ITEM_4 EQU $80

DEF TOGGLEMAP$C9_ID EQU $81
	DEF TOGGLEMAP$C9_NAME EQUS "ROCKET_HIDEOUT_B3F"
	; 81 X
DEF TOGGLE_ROCKET_HIDEOUT_B3F_ITEM_1 EQU $81
	; 82 X
DEF TOGGLE_ROCKET_HIDEOUT_B3F_ITEM_2 EQU $82

DEF TOGGLEMAP$CA_ID EQU $83
	DEF TOGGLEMAP$CA_NAME EQUS "ROCKET_HIDEOUT_B4F"
	; 83
DEF TOGGLE_ROCKET_HIDEOUT_B4F_GIOVANNI EQU $83
	; 84 X
DEF TOGGLE_ROCKET_HIDEOUT_B4F_ITEM_1 EQU $84
	; 85 X
DEF TOGGLE_ROCKET_HIDEOUT_B4F_ITEM_2 EQU $85
	; 86 X
DEF TOGGLE_ROCKET_HIDEOUT_B4F_ITEM_3 EQU $86
	; 87
DEF TOGGLE_ROCKET_HIDEOUT_B4F_ITEM_4 EQU $87
	; 88
DEF TOGGLE_ROCKET_HIDEOUT_B4F_ITEM_5 EQU $88

DEF TOGGLEMAP$CF_ID EQU $89
	DEF TOGGLEMAP$CF_NAME EQUS "SILPH_CO_2F"
	; 89 XXX never (de)activated?
DEF TOGGLE_SILPH_CO_2F_1 EQU $89
	; 8A
DEF TOGGLE_SILPH_CO_2F_2 EQU $8A
	; 8B
DEF TOGGLE_SILPH_CO_2F_3 EQU $8B
	; 8C
DEF TOGGLE_SILPH_CO_2F_4 EQU $8C
	; 8D
DEF TOGGLE_SILPH_CO_2F_5 EQU $8D

DEF TOGGLEMAP$D0_ID EQU $8E
	DEF TOGGLEMAP$D0_NAME EQUS "SILPH_CO_3F"
	; 8E
DEF TOGGLE_SILPH_CO_3F_1 EQU $8E
	; 8F
DEF TOGGLE_SILPH_CO_3F_2 EQU $8F
	; 90 X
DEF TOGGLE_SILPH_CO_3F_ITEM EQU $90

DEF TOGGLEMAP$D1_ID EQU $91
	DEF TOGGLEMAP$D1_NAME EQUS "SILPH_CO_4F"
	; 91
DEF TOGGLE_SILPH_CO_4F_1 EQU $91
	; 92
DEF TOGGLE_SILPH_CO_4F_2 EQU $92
	; 93
DEF TOGGLE_SILPH_CO_4F_3 EQU $93
	; 94 X
DEF TOGGLE_SILPH_CO_4F_ITEM_1 EQU $94
	; 95 X
DEF TOGGLE_SILPH_CO_4F_ITEM_2 EQU $95
	; 96 X
DEF TOGGLE_SILPH_CO_4F_ITEM_3 EQU $96

DEF TOGGLEMAP$D2_ID EQU $97
	DEF TOGGLEMAP$D2_NAME EQUS "SILPH_CO_5F"
	; 97
DEF TOGGLE_SILPH_CO_5F_1 EQU $97
	; 98
DEF TOGGLE_SILPH_CO_5F_2 EQU $98
	; 99
DEF TOGGLE_SILPH_CO_5F_3 EQU $99
	; 9A
DEF TOGGLE_SILPH_CO_5F_4 EQU $9A
	; 9B X
DEF TOGGLE_SILPH_CO_5F_ITEM_1 EQU $9B
	; 9C X
DEF TOGGLE_SILPH_CO_5F_ITEM_2 EQU $9C
	; 9D X
DEF TOGGLE_SILPH_CO_5F_ITEM_3 EQU $9D

DEF TOGGLEMAP$D3_ID EQU $9E
	DEF TOGGLEMAP$D3_NAME EQUS "SILPH_CO_6F"
	; 9E
DEF TOGGLE_SILPH_CO_6F_1 EQU $9E
	; 9F
DEF TOGGLE_SILPH_CO_6F_2 EQU $9F
	; A0
DEF TOGGLE_SILPH_CO_6F_3 EQU $A0
	; A1 X
DEF TOGGLE_SILPH_CO_6F_ITEM_1 EQU $A1
	; A2 X
DEF TOGGLE_SILPH_CO_6F_ITEM_2 EQU $A2

DEF TOGGLEMAP$D4_ID EQU $A3
	DEF TOGGLEMAP$D4_NAME EQUS "SILPH_CO_7F"
	; A3
DEF TOGGLE_SILPH_CO_7F_1 EQU $A3
	; A4
DEF TOGGLE_SILPH_CO_7F_2 EQU $A4
	; A5
DEF TOGGLE_SILPH_CO_7F_3 EQU $A5
	; A6
DEF TOGGLE_SILPH_CO_7F_4 EQU $A6
	; A7
DEF TOGGLE_SILPH_CO_7F_RIVAL EQU $A7
	; A8 X
DEF TOGGLE_SILPH_CO_7F_ITEM_1 EQU $A8
	; A9 X
DEF TOGGLE_SILPH_CO_7F_ITEM_2 EQU $A9
	; AA XXX sprite doesn't exist
DEF TOGGLE_SILPH_CO_7F_8 EQU $AA

DEF TOGGLEMAP$D5_ID EQU $AB
	DEF TOGGLEMAP$D5_NAME EQUS "SILPH_CO_8F"
	; AB
DEF TOGGLE_SILPH_CO_8F_1 EQU $AB
	; AC
DEF TOGGLE_SILPH_CO_8F_2 EQU $AC
	; AD
DEF TOGGLE_SILPH_CO_8F_3 EQU $AD

DEF TOGGLEMAP$E9_ID EQU $AE
	DEF TOGGLEMAP$E9_NAME EQUS "SILPH_CO_9F"
	; AE
DEF TOGGLE_SILPH_CO_9F_1 EQU $AE
	; AF
DEF TOGGLE_SILPH_CO_9F_2 EQU $AF
	; B0
DEF TOGGLE_SILPH_CO_9F_3 EQU $B0

DEF TOGGLEMAP$EA_ID EQU $B1
	DEF TOGGLEMAP$EA_NAME EQUS "SILPH_CO_10F"
	; B1
DEF TOGGLE_SILPH_CO_10F_1 EQU $B1
	; B2
DEF TOGGLE_SILPH_CO_10F_2 EQU $B2
	; B3 XXX never (de)activated?
DEF TOGGLE_SILPH_CO_10F_3 EQU $B3
	; B4 X
DEF TOGGLE_SILPH_CO_10F_ITEM_1 EQU $B4
	; B5 X
DEF TOGGLE_SILPH_CO_10F_ITEM_2 EQU $B5
	; B6 X
DEF TOGGLE_SILPH_CO_10F_ITEM_3 EQU $B6

DEF TOGGLEMAP$EB_ID EQU $B7
	DEF TOGGLEMAP$EB_NAME EQUS "SILPH_CO_11F"
	; B7
DEF TOGGLE_SILPH_CO_11F_1 EQU $B7
	; B8
DEF TOGGLE_SILPH_CO_11F_2 EQU $B8
	; B9
DEF TOGGLE_SILPH_CO_11F_3 EQU $B9

DEF TOGGLEMAP$F4_ID EQU $BA
	DEF TOGGLEMAP$F4_NAME EQUS "UNUSED_MAP_F4"
	; BA XXX sprite doesn't exist
DEF TOGGLE_UNUSED_MAP_F4_1 EQU $BA

DEF TOGGLEMAP$D6_ID EQU $BB
	DEF TOGGLEMAP$D6_NAME EQUS "POKEMON_MANSION_2F"
	; BB X
DEF TOGGLE_POKEMON_MANSION_2F_ITEM EQU $BB

DEF TOGGLEMAP$D7_ID EQU $BC
	DEF TOGGLEMAP$D7_NAME EQUS "POKEMON_MANSION_3F"
	; BC X
DEF TOGGLE_POKEMON_MANSION_3F_ITEM_1 EQU $BC
	; BD X
DEF TOGGLE_POKEMON_MANSION_3F_ITEM_2 EQU $BD

DEF TOGGLEMAP$D8_ID EQU $BE
	DEF TOGGLEMAP$D8_NAME EQUS "POKEMON_MANSION_B1F"
	; BE X
DEF TOGGLE_POKEMON_MANSION_B1F_ITEM_1 EQU $BE
	; BF X
DEF TOGGLE_POKEMON_MANSION_B1F_ITEM_2 EQU $BF
	; C0 X
DEF TOGGLE_POKEMON_MANSION_B1F_ITEM_3 EQU $C0
	; C1 X
DEF TOGGLE_POKEMON_MANSION_B1F_ITEM_4 EQU $C1
	; C2 X
DEF TOGGLE_POKEMON_MANSION_B1F_ITEM_5 EQU $C2

DEF TOGGLEMAP$D9_ID EQU $C3
	DEF TOGGLEMAP$D9_NAME EQUS "SAFARI_ZONE_EAST"
	; C3 X
DEF TOGGLE_SAFARI_ZONE_EAST_ITEM_1 EQU $C3
	; C4 X
DEF TOGGLE_SAFARI_ZONE_EAST_ITEM_2 EQU $C4
	; C5 X
DEF TOGGLE_SAFARI_ZONE_EAST_ITEM_3 EQU $C5
	; C6 X
DEF TOGGLE_SAFARI_ZONE_EAST_ITEM_4 EQU $C6

DEF TOGGLEMAP$DA_ID EQU $C7
	DEF TOGGLEMAP$DA_NAME EQUS "SAFARI_ZONE_NORTH"
	; C7 X
DEF TOGGLE_SAFARI_ZONE_NORTH_ITEM_1 EQU $C7
	; C8 X
DEF TOGGLE_SAFARI_ZONE_NORTH_ITEM_2 EQU $C8

DEF TOGGLEMAP$DB_ID EQU $C9
	DEF TOGGLEMAP$DB_NAME EQUS "SAFARI_ZONE_WEST"
	; C9 X
DEF TOGGLE_SAFARI_ZONE_WEST_ITEM_1 EQU $C9
	; CA X
DEF TOGGLE_SAFARI_ZONE_WEST_ITEM_2 EQU $CA
	; CB X
DEF TOGGLE_SAFARI_ZONE_WEST_ITEM_3 EQU $CB
	; CC X
DEF TOGGLE_SAFARI_ZONE_WEST_ITEM_4 EQU $CC

DEF TOGGLEMAP$DC_ID EQU $CD
	DEF TOGGLEMAP$DC_NAME EQUS "SAFARI_ZONE_CENTER"
	; CD X
DEF TOGGLE_SAFARI_ZONE_CENTER_ITEM EQU $CD

DEF TOGGLEMAP$E2_ID EQU $CE
	DEF TOGGLEMAP$E2_NAME EQUS "CERULEAN_CAVE_2F"
	; CE X
DEF TOGGLE_CERULEAN_CAVE_2F_ITEM_1 EQU $CE
	; CF X
DEF TOGGLE_CERULEAN_CAVE_2F_ITEM_2 EQU $CF
	; D0 X
DEF TOGGLE_CERULEAN_CAVE_2F_ITEM_3 EQU $D0

DEF TOGGLEMAP$E3_ID EQU $D1
	DEF TOGGLEMAP$E3_NAME EQUS "CERULEAN_CAVE_B1F"
	; D1 X
DEF TOGGLE_MEWTWO EQU $D1
	; D2 X
DEF TOGGLE_CERULEAN_CAVE_B1F_ITEM_1 EQU $D2
	; D3 X
DEF TOGGLE_CERULEAN_CAVE_B1F_ITEM_2 EQU $D3

DEF TOGGLEMAP$6C_ID EQU $D4
	DEF TOGGLEMAP$6C_NAME EQUS "VICTORY_ROAD_1F"
	; D4 X
DEF TOGGLE_VICTORY_ROAD_1F_ITEM_1 EQU $D4
	; D5 X
DEF TOGGLE_VICTORY_ROAD_1F_ITEM_2 EQU $D5

DEF TOGGLEMAP$78_ID EQU $D6
	DEF TOGGLEMAP$78_NAME EQUS "CHAMPIONS_ROOM"
	; D6
DEF TOGGLE_CHAMPIONS_ROOM_OAK EQU $D6

DEF TOGGLEMAP$C0_ID EQU $D7
	DEF TOGGLEMAP$C0_NAME EQUS "SEAFOAM_ISLANDS_1F"
	; D7
DEF TOGGLE_SEAFOAM_ISLANDS_1F_BOULDER_1 EQU $D7
	; D8
DEF TOGGLE_SEAFOAM_ISLANDS_1F_BOULDER_2 EQU $D8

DEF TOGGLEMAP$9F_ID EQU $D9
	DEF TOGGLEMAP$9F_NAME EQUS "SEAFOAM_ISLANDS_B1F"
	; D9
DEF TOGGLE_SEAFOAM_ISLANDS_B1F_BOULDER_1 EQU $D9
	; DA
DEF TOGGLE_SEAFOAM_ISLANDS_B1F_BOULDER_2 EQU $DA

DEF TOGGLEMAP$A0_ID EQU $DB
	DEF TOGGLEMAP$A0_NAME EQUS "SEAFOAM_ISLANDS_B2F"
	; DB
DEF TOGGLE_SEAFOAM_ISLANDS_B2F_BOULDER_1 EQU $DB
	; DC
DEF TOGGLE_SEAFOAM_ISLANDS_B2F_BOULDER_2 EQU $DC

DEF TOGGLEMAP$A1_ID EQU $DD
	DEF TOGGLEMAP$A1_NAME EQUS "SEAFOAM_ISLANDS_B3F"
	; DD
DEF TOGGLE_SEAFOAM_ISLANDS_B3F_BOULDER_1 EQU $DD
	; DE
DEF TOGGLE_SEAFOAM_ISLANDS_B3F_BOULDER_2 EQU $DE
	; DF
DEF TOGGLE_SEAFOAM_ISLANDS_B3F_BOULDER_3 EQU $DF
	; E0
DEF TOGGLE_SEAFOAM_ISLANDS_B3F_BOULDER_4 EQU $E0

DEF TOGGLEMAP$A2_ID EQU $E1
	DEF TOGGLEMAP$A2_NAME EQUS "SEAFOAM_ISLANDS_B4F"
	; E1
DEF TOGGLE_SEAFOAM_ISLANDS_B4F_BOULDER_1 EQU $E1
	; E2
DEF TOGGLE_SEAFOAM_ISLANDS_B4F_BOULDER_2 EQU $E2
	; E3 X
DEF TOGGLE_ARTICUNO EQU $E3

DEF NUM_TOGGLEABLE_OBJECTS EQU $E4
