; trainer data structure fields (see macros/scripts/maps.asm)
DEF TRAINER_EVENT_FLAG_BIT EQU 0 ;  0
DEF TRAINER_VIEW_RANGE EQU 1 ;  1
DEF TRAINER_EVENT_FLAG_POINTER EQU 2 ;  2
DEF TRAINER_BEFORE_BATTLE_TEXT EQU 4 ;  4
DEF TRAINER_AFTER_BATTLE_TEXT EQU 6 ;  6
DEF TRAINER_WON_BATTLE_TEXT EQU 8 ;  8
DEF TRAINER_LOST_BATTLE_TEXT EQU $A ; 10
DEF TRAINER_STRUCT_SIZE EQU $C ; 12
