DEF OPP_ID_OFFSET EQU 200


; trainer class ids
; indexes for:
; - TrainerNames (see data/trainers/names.asm)
; - TrainerNamePointers (see data/trainers/name_pointers.asm)
; - TrainerDataPointers (see data/trainers/parties.asm)
; - TrainerPicAndMoneyPointers (see data/trainers/pic_pointers_money.asm)
; - TrainerAIPointers (see data/trainers/ai_pointers.asm)
; - TrainerClassMoveChoiceModifications (see data/trainers/move_choices.asm)
	; $00
DEF NOBODY EQU 0
DEF OPP_NOBODY EQU $C8
	; $01
DEF YOUNGSTER EQU 1
DEF OPP_YOUNGSTER EQU $C9
	; $02
DEF BUG_CATCHER EQU 2
DEF OPP_BUG_CATCHER EQU $CA
	; $03
DEF LASS EQU 3
DEF OPP_LASS EQU $CB
	; $04
DEF SAILOR EQU 4
DEF OPP_SAILOR EQU $CC
	; $05
DEF JR_TRAINER_M EQU 5
DEF OPP_JR_TRAINER_M EQU $CD
	; $06
DEF JR_TRAINER_F EQU 6
DEF OPP_JR_TRAINER_F EQU $CE
	; $07
DEF POKEMANIAC EQU 7
DEF OPP_POKEMANIAC EQU $CF
	; $08
DEF SUPER_NERD EQU 8
DEF OPP_SUPER_NERD EQU $D0
	; $09
DEF HIKER EQU 9
DEF OPP_HIKER EQU $D1
	; $0A
DEF BIKER EQU $A
DEF OPP_BIKER EQU $D2
	; $0B
DEF BURGLAR EQU $B
DEF OPP_BURGLAR EQU $D3
	; $0C
DEF ENGINEER EQU $C
DEF OPP_ENGINEER EQU $D4
	; $0D
DEF UNUSED_JUGGLER EQU $D
DEF OPP_UNUSED_JUGGLER EQU $D5
	; $0E
DEF FISHER EQU $E
DEF OPP_FISHER EQU $D6
	; $0F
DEF SWIMMER EQU $F
DEF OPP_SWIMMER EQU $D7
	; $10
DEF CUE_BALL EQU $10
DEF OPP_CUE_BALL EQU $D8
	; $11
DEF GAMBLER EQU $11
DEF OPP_GAMBLER EQU $D9
	; $12
DEF BEAUTY EQU $12
DEF OPP_BEAUTY EQU $DA
	; $13
DEF PSYCHIC_TR EQU $13
DEF OPP_PSYCHIC_TR EQU $DB
	; $14
DEF ROCKER EQU $14
DEF OPP_ROCKER EQU $DC
	; $15
DEF JUGGLER EQU $15
DEF OPP_JUGGLER EQU $DD
	; $16
DEF TAMER EQU $16
DEF OPP_TAMER EQU $DE
	; $17
DEF BIRD_KEEPER EQU $17
DEF OPP_BIRD_KEEPER EQU $DF
	; $18
DEF BLACKBELT EQU $18
DEF OPP_BLACKBELT EQU $E0
	; $19
DEF RIVAL1 EQU $19
DEF OPP_RIVAL1 EQU $E1
	; $1A
DEF PROF_OAK EQU $1A
DEF OPP_PROF_OAK EQU $E2
	; $1B
DEF CHIEF EQU $1B
DEF OPP_CHIEF EQU $E3
	; $1C
DEF SCIENTIST EQU $1C
DEF OPP_SCIENTIST EQU $E4
	; $1D
DEF GIOVANNI EQU $1D
DEF OPP_GIOVANNI EQU $E5
	; $1E
DEF ROCKET EQU $1E
DEF OPP_ROCKET EQU $E6
	; $1F
DEF COOLTRAINER_M EQU $1F
DEF OPP_COOLTRAINER_M EQU $E7
	; $20
DEF COOLTRAINER_F EQU $20
DEF OPP_COOLTRAINER_F EQU $E8
	; $21
DEF BRUNO EQU $21
DEF OPP_BRUNO EQU $E9
	; $22
DEF BROCK EQU $22
DEF OPP_BROCK EQU $EA
	; $23
DEF MISTY EQU $23
DEF OPP_MISTY EQU $EB
	; $24
DEF LT_SURGE EQU $24
DEF OPP_LT_SURGE EQU $EC
	; $25
DEF ERIKA EQU $25
DEF OPP_ERIKA EQU $ED
	; $26
DEF KOGA EQU $26
DEF OPP_KOGA EQU $EE
	; $27
DEF BLAINE EQU $27
DEF OPP_BLAINE EQU $EF
	; $28
DEF SABRINA EQU $28
DEF OPP_SABRINA EQU $F0
	; $29
DEF GENTLEMAN EQU $29
DEF OPP_GENTLEMAN EQU $F1
	; $2A
DEF RIVAL2 EQU $2A
DEF OPP_RIVAL2 EQU $F2
	; $2B
DEF RIVAL3 EQU $2B
DEF OPP_RIVAL3 EQU $F3
	; $2C
DEF LORELEI EQU $2C
DEF OPP_LORELEI EQU $F4
	; $2D
DEF CHANNELER EQU $2D
DEF OPP_CHANNELER EQU $F5
	; $2E
DEF AGATHA EQU $2E
DEF OPP_AGATHA EQU $F6
	; $2F
DEF LANCE EQU $2F
DEF OPP_LANCE EQU $F7
DEF NUM_TRAINERS EQU $2F
